const MESSAGE='Здравствуйте! Подскажите, пожалуйста, есть ли ещё места в лагерь EXTREME KIDS Тропарёво на 17–21 августа?';
const dayData=[
{name:'Ваня',sport:'ролики',img:'assets/vanya.svg',kicker:'Понедельник • 17 августа',title:'Старт смены: знакомимся и включаемся в общий ритм',lead:'Первый день снимает напряжение и помогает ребёнку быстро почувствовать себя своим: знакомство, ролики, командное включение и понятный ритм лагеря.',slots:[['10:00','Сбор и знакомство','Встречаем детей и спокойно входим в общий ритм.'],['10:30','Командное включение','Игры, правила и первые совместные задачи.'],['11:15','Ролики с Ваней','Основной спортивный блок под уровень группы.'],['13:00','Обед','Питание, вода и полноценная пауза.'],['14:00','Игры / специальный блок','Меняем формат, чтобы сохранить энергию и интерес.'],['16:30','Полдник и финал','Спокойное завершение и итоги дня.']]},
{name:'Стас',sport:'ролики',img:'assets/stas.svg',kicker:'Вторник • 18 августа',title:'День движения, техники и уверенного прогресса',lead:'Во второй день группа уже знакома. Добавляем динамику, спортивные задачи, координацию и ощущение собственного прогресса.',slots:[['10:00','Старт дня','Быстро включаемся и собираем фокус группы.'],['10:30','Разминка','Активный старт с игровыми задачами.'],['11:15','Ролики со Стасом','Техника, координация и уверенность.'],['13:00','Обед','Питание и восстановление.'],['14:00','Игры и эстафеты','Командный азарт без однообразия.'],['16:30','Полдник и завершение','Снижаем темп и красиво заканчиваем день.']]},
{name:'Тася',sport:'ролики',img:'assets/tasya.svg',kicker:'Среда • 19 августа',title:'Середина смены: команда уже сложилась',lead:'К середине недели дети уже чувствуют себя командой. Сохраняем спортивный ритм и добавляем новые впечатления и специальный формат.',slots:[['10:00','Сбор группы','Встречаемся и вспоминаем план дня.'],['10:30','Утреннее включение','Игры, разминка и подготовка.'],['11:15','Ролики с Тасей','Основной спортивный блок.'],['13:00','Обед','Питание и отдых.'],['14:00','Гостевой / интерактивный блок','Одна из специальных активностей смены.'],['16:30','Полдник','Переключение перед завершением.']]},
{name:'Тася',sport:'ролики',img:'assets/tasya.svg',kicker:'Четверг • 20 августа',title:'День команды, энергии и новых впечатлений',lead:'Дети уже смелее и свободнее. Используем эту энергию для ярких задач, роликов, игр и ещё одного запоминающегося дня.',slots:[['10:00','Старт','Собираемся и включаемся.'],['10:30','Активная разминка','Подвижные задачи и подготовка.'],['11:15','Ролики с Тасей','Продолжаем развивать технику и уверенность.'],['13:00','Обед','Пауза на питание и восстановление.'],['14:00','Специальный блок','Дополнительная яркая активность недели.'],['16:30','Полдник и финал','Плавно снижаем темп и завершаем день.']]},
{name:'Доминик + Женя',sport:'скейт',img:'assets/dominik-zhenya.svg',kicker:'Пятница • 21 августа',title:'Финал недели: скейт, команда и сильная точка',lead:'Последний день ведут сразу два наставника. Больше внимания, больше командной динамики и яркое завершение всей истории лагеря.',slots:[['10:00','Сбор финального дня','Задаём настроение пятнице.'],['10:30','Разминка и игра','Включаем всю группу.'],['11:15','Скейт с Домиником и Женей','Активная часть с двумя наставниками.'],['13:00','Обед','Пауза на питание и отдых.'],['14:00','Финальный командный блок','Эмоциональный пик смены.'],['16:30','Итоги недели','Вспоминаем лучшие моменты и завершаем смену.']]}
];
const tabs=[...document.querySelectorAll('.day-tab')],frame=document.getElementById('mentorFrame'),img=document.getElementById('mentorImage'),nameEl=document.getElementById('mentorName'),sportEl=document.getElementById('mentorSport'),kickerEl=document.getElementById('dayKicker'),titleEl=document.getElementById('dayTitle'),leadEl=document.getElementById('dayLead'),timeline=document.getElementById('timeline');
function renderSlots(items){timeline.innerHTML=items.map(s=>`<div class="slot"><time>${s[0]}</time><div><b>${s[1]}</b><span>${s[2]}</span></div></div>`).join('')}
function renderDay(i){const d=dayData[i];tabs.forEach((t,j)=>t.classList.toggle('active',j===i));frame.classList.add('switching');const preload=new Image();preload.src=d.img;preload.onload=()=>setTimeout(()=>{img.src=d.img;img.alt=d.name;nameEl.textContent=d.name;sportEl.textContent=d.sport;kickerEl.textContent=d.kicker;titleEl.textContent=d.title;leadEl.textContent=d.lead;renderSlots(d.slots);frame.classList.remove('switching')},120)}
tabs.forEach((t,i)=>t.addEventListener('click',()=>renderDay(i)));renderSlots(dayData[0].slots);
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('show');observer.unobserve(e.target)}}),{threshold:.11});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const progress=document.getElementById('pageProgress');addEventListener('scroll',()=>{const d=document.documentElement;const max=d.scrollHeight-innerHeight;progress.style.width=(max>0?scrollY/max*100:0)+'%'},{passive:true});
const glow=document.getElementById('pointerGlow');addEventListener('pointermove',e=>{glow.style.left=e.clientX+'px';glow.style.top=e.clientY+'px'},{passive:true});
if(matchMedia('(hover:hover)').matches){document.querySelectorAll('[data-tilt]').forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5;const y=(e.clientY-r.top)/r.height-.5;el.style.transform=`perspective(1000px) rotateY(${x*4}deg) rotateX(${-y*4}deg) translateY(-3px)`});el.addEventListener('pointerleave',()=>el.style.transform='')})}
const toast=document.getElementById('toast');function showToast(t){toast.textContent=t;toast.classList.add('show');clearTimeout(window.__tt);window.__tt=setTimeout(()=>toast.classList.remove('show'),1800)}
function copyMessage(show=true){navigator.clipboard?.writeText(MESSAGE).then(()=>{if(show)showToast('Сообщение скопировано')}).catch(()=>{if(show)prompt('Скопируйте сообщение:',MESSAGE)})}
function sharePage(){if(navigator.share){navigator.share({title:document.title,text:'Лагерь EXTREME KIDS Тропарёво 17–21 августа',url:location.href}).catch(()=>{})}else navigator.clipboard?.writeText(location.href).then(()=>showToast('Ссылка скопирована'))}
window.copyMessage=copyMessage;window.sharePage=sharePage;
addEventListener('load',()=>setTimeout(()=>document.getElementById('intro').classList.add('hide'),650));
