(()=>{
const money=n=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:0}).format(Math.round(Number(n)||0))+' ₽';
const pct=n=>Math.round(Number(n)||0)+'%';
const state=()=>window.appState||window.state||window.db||{};
const firstNum=(...v)=>{for(const x of v){const n=Number(x);if(Number.isFinite(n)&&n>=0)return n}return 0};
const path=(o,p)=>p.split('.').reduce((a,k)=>a&&a[k],o);
function revenue(s){return firstNum(path(s,'growthOS.currentRevenue'),path(s,'growthOS.finance.revenue'),path(s,'finance.revenue'),path(s,'month.revenue'),path(s,'stats.revenue'),path(s,'revenue'))}
function plan(s){return firstNum(path(s,'growthOS.currentPlan'),path(s,'growthOS.finance.plan'),path(s,'finance.plan'),path(s,'month.plan'),3800000)}
function groups(s){let g=path(s,'growthOS.groups')||path(s,'groups')||[];return Array.isArray(g)?g:[]}
function tasks(s){let t=path(s,'tasks')||path(s,'growthOS.tasks')||[];return Array.isArray(t)?t:[]}
function events(s){let e=path(s,'events')||path(s,'growthOS.events')||[];return Array.isArray(e)?e:[]}
function history(s){let h=path(s,'growthOS.history.daily')||[];return Array.isArray(h)?h:[]}
function archive(s){let a=path(s,'growthOS.archive')||[];return Array.isArray(a)?a:[]}
function loadStats(s){const gs=groups(s);let cap=0,used=0;gs.forEach(g=>{cap+=firstNum(g.capacity,g.max,g.limit);used+=firstNum(g.children,g.current,g.count)});return{cap,used,load:cap?used/cap*100:0,free:Math.max(0,cap-used)}}
function taskStats(s){const ts=tasks(s),done=ts.filter(t=>/done|готов|выполн/i.test(String(t.status||''))).length,over=ts.filter(t=>{if(/done|готов|выполн/i.test(String(t.status||'')))return false;const d=new Date(t.deadline||t.due||0);return d&&+d< Date.now()}).length;return{total:ts.length,done,over,progress:ts.length?done/ts.length*100:0}}
function forecast(s){const now=new Date(),r=revenue(s),p=plan(s),days=new Date(now.getFullYear(),now.getMonth()+1,0).getDate(),day=Math.max(1,now.getDate());let base=r/day*days;const h=history(s).filter(x=>x&&x.revenue!=null).slice(-10);if(h.length>=4){const vals=h.map(x=>Number(x.revenue)||0);const deltas=vals.slice(1).map((v,i)=>Math.max(0,v-vals[i]));const avg=deltas.slice(-5).reduce((a,b)=>a+b,0)/Math.max(1,deltas.slice(-5).length);base=r+avg*(days-day)}return{r,p,day,days,base,low:base*.88,high:base*1.14,gap:Math.max(0,p-r),pace:p?base/p*100:0}}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function lineChart(points,target){const W=760,H=220,P=28;if(!points.length)points=[0];const vals=points.map(Number),max=Math.max(target||0,...vals,1)*1.08,min=0;const xy=vals.map((v,i)=>[P+(W-2*P)*(i/Math.max(1,vals.length-1)),H-P-(H-2*P)*((v-min)/(max-min))]);const line=xy.map((p,i)=>(i?'L':'M')+p[0].toFixed(1)+' '+p[1].toFixed(1)).join(' ');const area=line+' L '+(W-P)+' '+(H-P)+' L '+P+' '+(H-P)+' Z';const ty=H-P-(H-2*P)*(target/max);return `<svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none"><defs><linearGradient id="ek54gold" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#efd56f"/><stop offset="1" stop-color="#d8b947" stop-opacity="0"/></linearGradient></defs><line class="ek54-axis" x1="${P}" y1="${H-P}" x2="${W-P}" y2="${H-P}"/><line x1="${P}" y1="${ty}" x2="${W-P}" y2="${ty}" stroke="#6f5a1f" stroke-dasharray="7 6"/><path class="ek54-area" d="${area}"/><path class="ek54-line" d="${line}"/>${xy.map(p=>`<circle class="ek54-dot" cx="${p[0]}" cy="${p[1]}" r="4"/>`).join('')}</svg>`}
function bars(vals,labels){const W=460,H=220,P=30,max=Math.max(...vals,1)*1.1,bw=(W-2*P)/vals.length*.56;return `<svg viewBox="0 0 ${W} ${H}">${vals.map((v,i)=>{const slot=(W-2*P)/vals.length,x=P+i*slot+(slot-bw)/2,h=(H-60)*v/max,y=H-35-h;return `<rect class="ek54-bar ${i===1?'hot':'soft'}" x="${x}" y="${y}" width="${bw}" height="${h}" rx="7"/><text x="${x+bw/2}" y="${H-14}" fill="#a89c84" text-anchor="middle" font-size="11">${esc(labels[i])}</text><text x="${x+bw/2}" y="${Math.max(14,y-8)}" fill="#efd56f" text-anchor="middle" font-size="12" font-weight="800">${(v/1e6).toFixed(1)}м</text>`}).join('')}</svg>`}
function recoData(s,f,ls,ts){const a=[];if(f.base<2500000)a.push('Текущий темп ведёт ниже минимального пола 2,5 млн ₽ — нужно усиливать продажи уже сейчас.');else if(f.base<f.p)a.push(`До плана по текущему прогнозу не хватает примерно ${money(f.p-f.base)}.`);else a.push('Текущий темп выше плана. Задача — удержать продажи и не просадить загрузку групп.');if(ls.cap&&ls.load<75)a.push(`Средняя загрузка ${pct(ls.load)}. Свободно ${ls.free} мест — это главный резерв роста без расширения расписания.`);if(ts.over)a.push(`Просрочено задач: ${ts.over}. Их закрытие влияет на исполнение плана и дисциплину команды.`);if(!groups(s).length)a.push('Заполните вместимость и текущую численность групп — тогда аналитика покажет реальную загрузку и потерянную выручку.');return a}
function analyticsHTML(){const s=state(),f=forecast(s),ls=loadStats(s),ts=taskStats(s),h=history(s),hist=h.length?h.map(x=>Number(x.revenue)||0):[0,f.r*.18,f.r*.38,f.r*.61,f.r*.82,f.r],recos=recoData(s,f,ls,ts);const status=f.base>=f.p?'Темп выше плана':f.base>=2500000?'Рабочая зона':'Ниже безопасного пола';return `<div class="ek54-analytics"><section class="ek54-hero"><div class="ek54-hero-top"><div><div class="ek54-kicker">АНАЛИТИКА · ТЕКУЩИЙ МЕСЯЦ</div><h2>Прогноз выручки</h2><div class="ek54-sub">Расчёт обновляется по текущему факту и накопленной дневной истории</div></div><div><div class="ek54-forecast">${money(f.base)}</div><div class="ek54-sub">${esc(status)} · ${Math.round(f.pace)}% от цели</div></div></div><div class="ek54-scenarios"><div class="ek54-scenario"><span class="ek54-label">Осторожный</span><b>${money(f.low)}</b><small class="ek54-sub">−12% к базовому темпу</small></div><div class="ek54-scenario active"><span class="ek54-label">Базовый</span><b>${money(f.base)}</b><small class="ek54-sub">текущий темп</small></div><div class="ek54-scenario"><span class="ek54-label">Сильный</span><b>${money(f.high)}</b><small class="ek54-sub">+14% к базовому темпу</small></div></div></section><div class="ek54-grid4"><div class="ek54-stat"><span class="ek54-label">Факт</span><b>${money(f.r)}</b><small class="ek54-sub">на ${f.day}-й день месяца</small></div><div class="ek54-stat"><span class="ek54-label">План</span><b>${money(f.p)}</b><small class="ek54-sub">цель месяца</small></div><div class="ek54-stat"><span class="ek54-label">Загрузка</span><b>${pct(ls.load)}</b><small class="ek54-sub">${ls.free} свободных мест</small></div><div class="ek54-stat"><span class="ek54-label">Задачи</span><b>${pct(ts.progress)}</b><small class="ek54-sub">${ts.done}/${ts.total} · просрочено ${ts.over}</small></div></div><div class="ek54-charts"><section class="ek54-panel"><h3>Динамика выручки</h3><div class="ek54-sub">Жёлтая линия — факт/история, пунктир — план</div><div class="ek54-chart">${lineChart(hist,f.p)}</div></section><section class="ek54-panel"><h3>Сценарии конца месяца</h3><div class="ek54-sub">Прогноз при разной интенсивности продаж</div><div class="ek54-chart">${bars([f.low,f.base,f.high],['Осторожный','Базовый','Сильный'])}</div></section></div><section class="ek54-panel"><h3>Что делать по текущим показателям</h3><div class="ek54-recos">${recos.map(x=>`<div class="ek54-reco"><i></i><span>${esc(x)}</span></div>`).join('')}</div></section></div>`}
function archiveHTML(){const s=state(),a=archive(s);if(!a.length)return `<div class="ek54-analytics"><section class="ek54-hero"><div class="ek54-kicker">АРХИВ УЧЕБНОГО ГОДА</div><h2>История месяцев</h2><div class="ek54-sub">После закрытия месяца здесь сохраняются план, факт, загрузка, задачи и мероприятия.</div></section><div class="ek54-empty">Архив пока пуст. Первый полный месяц появится после закрытия сентября.</div></div>`;return `<div class="ek54-analytics"><section class="ek54-hero"><div class="ek54-kicker">АРХИВ УЧЕБНОГО ГОДА</div><h2>История месяцев</h2></section><div class="ek54-archive-grid">${a.slice().reverse().map(m=>`<div class="ek54-archive-card"><span class="ek54-label">${esc(m.month||m.label||'Месяц')}</span><b>${money(m.revenue||m.fact)}</b><div class="ek54-sub">План ${money(m.plan)} · загрузка ${pct(m.load)} · задачи ${pct(m.tasks)}</div></div>`).join('')}</div></div>`}
function container(){return document.querySelector('#pages')||document.querySelector('.content')||document.querySelector('main')}
function title(t){const x=document.querySelector('#pageTitle');if(x)x.textContent=t}
function show(kind){const c=container();if(!c)return;c.innerHTML=kind==='archive'?archiveHTML():analyticsHTML();title(kind==='archive'?'Архив':'Аналитика и прогноз');window.scrollTo({top:0,behavior:'smooth'})}
function makeNav(){const nav=document.querySelector('#nav')||document.querySelector('.nav');if(!nav)return;const has=t=>[...nav.querySelectorAll('button,a')].some(x=>x.textContent.includes(t));if(!has('Аналитика')){const b=document.createElement('button');b.innerHTML='<span class="ico">◈</span><span>Аналитика и прогноз</span>';b.dataset.ek54='analytics';nav.appendChild(b)}if(!has('Архив')){const b=document.createElement('button');b.innerHTML='<span class="ico">▣</span><span>Архив</span>';b.dataset.ek54='archive';nav.appendChild(b)}}
document.addEventListener('click',e=>{const b=e.target.closest('button,a');if(!b)return;const txt=b.textContent.trim();if(b.dataset.ek54==='analytics'||txt.includes('Аналитика и прогноз')){e.preventDefault();e.stopImmediatePropagation();show('analytics')}if(b.dataset.ek54==='archive'||(/^Архив/.test(txt))){e.preventDefault();e.stopImmediatePropagation();show('archive')}},true);
function snapshot(){const s=state();if(!s||typeof s!=='object')return;s.growthOS=s.growthOS||{};s.growthOS.history=s.growthOS.history||{};s.growthOS.history.daily=Array.isArray(s.growthOS.history.daily)?s.growthOS.history.daily:[];const d=new Date().toISOString().slice(0,10),r=revenue(s),ls=loadStats(s),ts=taskStats(s),last=s.growthOS.history.daily[s.growthOS.history.daily.length-1];if(!last||last.date!==d){s.growthOS.history.daily.push({date:d,revenue:r,load:ls.load,tasks:ts.progress});if(s.growthOS.history.daily.length>400)s.growthOS.history.daily=s.growthOS.history.daily.slice(-400);try{if(typeof window.saveDb==='function')window.saveDb()}catch(_){}}}
function init(){makeNav();snapshot();const t=document.body.innerText||'';if(t.includes('Аналитика и прогноз')&&document.querySelector('#pageTitle')?.textContent.includes('Аналитика'))show('analytics')}
setTimeout(init,900);setInterval(makeNav,2500);window.EKGrowthIntelligence={showAnalytics:()=>show('analytics'),showArchive:()=>show('archive'),forecast:()=>forecast(state())};
})();