(()=>{
'use strict';
const C=window.EK61,V=window.EK61_VIEWS;
const $=(sel,root=document)=>root.querySelector(sel),$$=(sel,root=document)=>[...root.querySelectorAll(sel)];
const today=()=>new Date().toISOString().slice(0,10);
const monthStart=month=>`${month}-01`;
const monthEnd=month=>{const [y,m]=month.split('-').map(Number);return `${month}-${String(new Date(y,m,0).getDate()).padStart(2,'0')}`};
const navCatalog={
 dashboard:{label:'Главная Романа',icon:'⌂',section:'Стратегия'},manager:{label:'Кабинет Софы',icon:'◆',section:'Стратегия'},year:{label:'Учебный год',icon:'▦',section:'Стратегия'},groups:{label:'Группы и загрузка',icon:'◉',section:'Управление'},goals:{label:'План развития',icon:'◎',section:'Управление'},tasks:{label:'Задачи',icon:'✓',section:'Управление'},calendar:{label:'Календарь',icon:'□',section:'Управление'},analytics:{label:'Аналитика и прогноз',icon:'↗',section:'Аналитика'},archive:{label:'Архив',icon:'▤',section:'Аналитика'},stas:{label:'Кабинет Стаса',icon:'СТ',section:'Кабинеты'},mentor:{label:'Наставники',icon:'Н',section:'Кабинеты'},admin:{label:'Администраторы',icon:'А',section:'Кабинеты'},team:{label:'Командный экран',icon:'★',section:'Кабинеты'},settings:{label:'Настройки',icon:'⚙',section:'Система'}
};
const roleViews={owner:['dashboard','manager','year','groups','goals','tasks','calendar','analytics','archive','stas','mentor','admin','team','settings'],manager:['manager','year','groups','goals','tasks','calendar','analytics','archive','stas','mentor','admin','team','settings'],head:['stas','groups','goals','tasks','calendar','analytics','mentor','team','settings'],mentor:['mentor','groups','tasks','calendar','team','settings'],admin:['admin','tasks','calendar','team','settings'],team:['team','calendar']};
const ui={month:C.monthKey(),view:'dashboard',taskMode:'month',taskOwner:'all',taskPriority:'all',taskSearch:'',groupSearch:'',groupDirection:'all',groupMentor:'all',mentorId:null,adminId:null,sidebar:false,...C.loadUI()};
window.EK61_APP={ui,render,navigate,toast,openModal,closeModal};
let draggedTask=null,renderQueued=false;
function persistUI(){C.saveUI(ui)}
function allowedViews(){return roleViews[C.effectiveRole()]||roleViews.team}
function homeView(){return C.ROLE_HOME[C.effectiveRole()]||allowedViews()[0]}
function ensureView(){if(!allowedViews().includes(ui.view))ui.view=homeView();if(!C.getState()?.months?.[ui.month])ui.month=Object.keys(C.getState()?.months||{}).sort()[0]||C.monthKey()}
function buildNav(){
 const nav=$('#mainNav'),views=allowedViews(),groups=[];let last='';for(const id of views){const item=navCatalog[id];if(!item)continue;if(item.section!==last){groups.push(`<div class="nav-section">${item.section}</div>`);last=item.section}const badge=id==='tasks'?C.scopedTasks(ui.month,'month').filter(t=>t.status!=='done').length:id==='groups'?C.scopedGroups().reduce((s,g)=>s+Math.max(0,Number(g.capacity||0)-Number(g.students||0)),0):'';groups.push(`<button class="nav-btn ${ui.view===id?'active':''}" data-view="${id}"><span class="nav-icon">${item.icon}</span><span class="nav-label">${item.label}</span>${badge!==''?`<span class="nav-badge">${badge}</span>`:''}</button>`)}nav.innerHTML=groups.join('');
 const mobile=$('#mobileNav'),mobileIds=views.filter(x=>['dashboard','manager','stas','mentor','admin','team','tasks','calendar','analytics'].includes(x)).slice(0,5);mobile.innerHTML=mobileIds.map(id=>`<button class="${ui.view===id?'active':''}" data-view="${id}"><span>${navCatalog[id].icon}</span><span>${navCatalog[id].label.split(' ')[0]}</span></button>`).join('');mobile.classList.remove('hidden');
}
function buildMonthSelect(){const select=$('#monthSelect'),months=Object.keys(C.getState().months||{}).sort();select.innerHTML=months.map(key=>`<option value="${key}" ${key===ui.month?'selected':''}>${C.monthLabel(key)}</option>`).join('')}
function buildProfile(){const u=C.currentUser(),role=C.ROLE_NAMES[C.effectiveRole()]||u.title;$('#sideAvatar').textContent=u.short||'—';$('#sideName').textContent=u.name;$('#sideRole').textContent=u.title||role;$('#topAvatar').textContent=u.short||'—';$('#topName').textContent=u.name;$('#topRole').textContent=role;const pop=$('#rolePopover');const items=C.effectiveRole()==='owner'?[['dashboard','roman','Роман · штаб собственника'],['manager','sofa','Софа · управляющая'],['stas','stas','Стас · руководитель'],['mentor','ivan','Кабинет наставника'],['admin','anya','Кабинет администратора'],['team','team','Командный экран']]:[[homeView(),u.id,`${u.name} · ${role}`]];pop.innerHTML=items.map(([view,id,label])=>`<button data-action="previewProfile" data-view-target="${view}" data-user="${id}">${label}</button>`).join('')}
function render(){
 if(renderQueued)return;renderQueued=true;requestAnimationFrame(()=>{renderQueued=false;ensureView();buildNav();buildMonthSelect();buildProfile();const meta=V.pageMeta[ui.view]||['Growth OS',''];$('#pageTitle').textContent=meta[0];$('#pageCrumb').textContent=meta[1]||'EXTREME KIDS · ТРОПАРЁВО';$('#pages').innerHTML=V.render(ui.view,{ui,month:ui.month});persistUI();bindDragDrop()})
}
function navigate(view){if(!allowedViews().includes(view))return;ui.view=view;ui.sidebar=false;$('#sidebar').classList.remove('open');$('#sidebarScrim').classList.add('hidden');render();scrollTo({top:0,behavior:'smooth'})}
function toast(message,type=''){const stack=$('#toastStack'),node=document.createElement('div');node.className=`toast ${type}`;node.textContent=message;stack.appendChild(node);setTimeout(()=>{node.style.opacity='0';node.style.transform='translateX(12px)'},2500);setTimeout(()=>node.remove(),2900)}
function openModal(title,subtitle,body,kicker='EXTREME KIDS'){$('#modalTitle').textContent=title;$('#modalSubtitle').textContent=subtitle||'';$('#modalKicker').textContent=kicker;$('#modalBody').innerHTML=body;$('#modal').classList.remove('hidden');$('#modal').setAttribute('aria-hidden','false');setTimeout(()=>$('#modal input:not([type=hidden]),#modal select,#modal textarea')?.focus(),30)}
function closeModal(){$('#modal').classList.add('hidden');$('#modal').setAttribute('aria-hidden','true');$('#modalBody').innerHTML=''}
function optionsUsers(selected='',kind='all'){
 const role=C.effectiveRole(),me=C.currentUser();let users=C.visible(C.getState().users).filter(u=>u.active!==false&&u.role!=='team');
 if(kind==='admin')users=users.filter(u=>u.role==='admin');else if(kind==='mentor')users=users.filter(u=>u.role==='mentor'||u.role==='head');
 else if(role==='manager')users=users.filter(u=>['manager','head','mentor','admin'].includes(u.role));else if(role==='head')users=users.filter(u=>u.id===me.id||(u.direction===me.direction&&u.role==='mentor'));else if(['mentor','admin'].includes(role))users=users.filter(u=>u.id===me.id);
 return users.map(u=>`<option value="${V.esc(u.id)}" ${u.id===selected?'selected':''}>${V.esc(u.name)} · ${V.esc(u.title)}</option>`).join('')
}
function taskForm(task=null,defaults={}){
 const t=task||{},selectedOwner=t.ownerId||defaults.ownerId||C.currentUser().id,deadline=t.deadline||defaults.deadline||monthEnd(ui.month);return `<form class="form-grid" id="taskForm" data-id="${V.esc(t.id||'')}"><div class="field full"><label>Задача</label><input class="input" name="title" required maxlength="160" value="${V.esc(t.title||defaults.title||'')}" placeholder="Конкретный результат"></div><div class="field full"><label>Описание</label><textarea class="textarea" name="description" placeholder="Что именно должно быть сделано">${V.esc(t.description||'')}</textarea></div><div class="field"><label>Ответственный</label><select class="select" name="ownerId">${optionsUsers(selectedOwner)}</select></div><div class="field"><label>Дедлайн</label><input class="input" type="date" name="deadline" value="${V.esc(deadline)}"></div><div class="field"><label>Месяц задачи</label><select class="select" name="month">${Object.keys(C.getState().months).sort().map(k=>`<option value="${k}" ${(t.month||ui.month)===k?'selected':''}>${C.monthLabel(k)}</option>`).join('')}</select></div><div class="field"><label>Приоритет</label><select class="select" name="priority">${Object.entries(C.PRIORITY).map(([k,v])=>`<option value="${k}" ${(t.priority||defaults.priority||'normal')===k?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label>Статус</label><select class="select" name="status">${C.STATUS_ORDER.map(k=>`<option value="${k}" ${(t.status||'todo')===k?'selected':''}>${C.TASK_STATUS[k]}</option>`).join('')}</select></div><div class="field"><label>Связать с целью</label><select class="select" name="goalId"><option value="">Без связи</option>${C.visible(C.getState().goals).map(g=>`<option value="${V.esc(g.id)}" ${t.goalId===g.id?'selected':''}>${V.esc(g.title)}</option>`).join('')}</select></div><div class="field"><label>Связать с группой</label><select class="select" name="groupId"><option value="">Без связи</option>${C.scopedGroups().map(g=>`<option value="${V.esc(g.id)}" ${t.groupId===g.id?'selected':''}>${V.esc(C.findUser(g.mentorId)?.name||'')} · ${V.esc(g.name)}</option>`).join('')}</select></div><div class="form-actions"><button type="button" class="btn btn-ghost" data-action="closeModal">Отмена</button><button class="btn btn-primary" type="submit">${task?'Сохранить':'Создать задачу'}</button></div></form>`}
function openTask(task=null,defaults={}){if(!C.can(task?'task.edit':'task.create',task)){toast('Недостаточно прав','error');return}openModal(task?'Редактировать задачу':'Новая задача',`Рабочий месяц: ${C.monthLabel(ui.month)}`,taskForm(task,defaults),'ЗАДАЧИ')}
function groupForm(group=null){const g=group||{};return `<form class="form-grid" id="groupForm" data-id="${V.esc(g.id||'')}"><div class="field"><label>Наставник</label><select class="select" name="mentorId">${optionsUsers(g.mentorId||C.currentUser().id,'mentor')}</select></div><div class="field"><label>Направление</label><select class="select" name="direction">${[['rollers','Ролики'],['bike','ВЕЛО / BMX'],['skate','Скейт']].map(([k,v])=>`<option value="${k}" ${(g.direction||C.currentUser().direction||'rollers')===k?'selected':''}>${v}</option>`).join('')}</select></div><div class="field full"><label>Название группы</label><input class="input" name="name" required value="${V.esc(g.name||'')}" placeholder="БАЗА / БАЗА+ / СПОРТ"></div><div class="field"><label>День недели</label><select class="select" name="day">${['Понедельник','Вторник','Среда','Четверг','Пятница','Суббота','Воскресенье'].map(x=>`<option ${g.day===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Время</label><input class="input" name="time" required value="${V.esc(g.time||'')}" placeholder="18:00"></div><div class="field"><label>Детей сейчас</label><input class="input" type="number" name="students" min="0" max="99" value="${Number(g.students||0)}"></div><div class="field"><label>Вместимость</label><input class="input" type="number" name="capacity" min="1" max="99" value="${Number(g.capacity||8)}"></div><div class="form-actions"><button type="button" class="btn btn-ghost" data-action="closeModal">Отмена</button><button class="btn btn-primary" type="submit">Сохранить группу</button></div></form>`}
function openGroup(group=null){if(!C.can('group.edit',group)){toast('Недостаточно прав','error');return}openModal(group?'Изменить группу':'Новая группа','Дети и вместимость сразу пересчитаются во всех кабинетах',groupForm(group),'ГРУППЫ')}
function saleForm(sale=null){const s=sale||{};return `<form class="form-grid" id="saleForm" data-id="${V.esc(s.id||'')}"><div class="field"><label>Дата</label><input class="input" type="date" name="date" required value="${V.esc(s.date||today())}"></div><div class="field"><label>Администратор</label><select class="select" name="adminId">${optionsUsers(s.adminId||C.currentUser().id,'admin')}</select></div><div class="field full"><label>Клиент / ребёнок</label><input class="input" name="clientName" required value="${V.esc(s.clientName||'')}" placeholder="Имя клиента"></div><div class="field"><label>Тип продажи</label><select class="select" name="type">${[['subscription','Абонемент'],['renewal','Продление'],['trial','Пробная'],['event','Мероприятие'],['camp','Лагерь'],['individual','Индивидуальная'],['other','Другое']].map(([k,v])=>`<option value="${k}" ${(s.type||'subscription')===k?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label>Сумма</label><input class="input" type="number" name="amount" min="0" step="100" required value="${Number(s.amount||0)}"></div><div class="field full"><label>Комментарий</label><textarea class="textarea" name="note">${V.esc(s.note||'')}</textarea></div><div class="form-actions"><button type="button" class="btn btn-ghost" data-action="closeModal">Отмена</button><button class="btn btn-primary" type="submit">Сохранить продажу</button></div></form>`}
function openSale(sale=null){if(!C.can('sale.edit')){toast('Недостаточно прав','error');return}openModal(sale?'Изменить продажу':'Добавить продажу','Выручка, прогноз и цели обновятся автоматически',saleForm(sale),'ПРОДАЖИ')}
function leadForm(){return `<form class="form-grid" id="leadForm"><div class="field"><label>Дата</label><input class="input" type="date" name="date" value="${today()}"></div><div class="field"><label>Администратор</label><select class="select" name="adminId">${optionsUsers(C.currentUser().id,'admin')}</select></div><div class="field full"><label>Клиент</label><input class="input" name="clientName" required></div><div class="field"><label>Этап</label><select class="select" name="stage"><option value="new">Новый лид</option><option value="trial">Записан на пробную</option><option value="expiring">Заканчивается абонемент</option><option value="renewal">Нужно продление</option><option value="lost">Отказ</option></select></div><div class="field"><label>Телефон / контакт</label><input class="input" name="contact"></div><div class="form-actions"><button type="button" class="btn btn-ghost" data-action="closeModal">Отмена</button><button class="btn btn-primary">Добавить лид</button></div></form>`}
function recommendationForm(){const mentor=C.effectiveRole()==='mentor'?C.currentUser().id:(ui.mentorId||'ivan');return `<form class="form-grid" id="recommendationForm"><div class="field"><label>Наставник</label><select class="select" name="mentorId">${optionsUsers(mentor,'mentor')}</select></div><div class="field"><label>Администратор</label><select class="select" name="adminId">${optionsUsers('anya','admin')}</select></div><div class="field full"><label>Ребёнок</label><input class="input" name="childName" required placeholder="Имя ребёнка"></div><div class="field full"><label>Рекомендация</label><select class="select" name="recommendation"><option>Переход в БАЗА+</option><option>Второе занятие в неделю</option><option>Спорт-группа</option><option>Индивидуальное занятие</option><option>Соревнования</option><option>Сборы / лагерь</option><option>Экипировка</option></select></div><div class="field full"><label>Комментарий наставника</label><textarea class="textarea" name="note"></textarea></div><div class="form-actions"><button type="button" class="btn btn-ghost" data-action="closeModal">Отмена</button><button class="btn btn-primary">Передать администратору</button></div></form>`}
function eventForm(event=null){const e=event||{};return `<form class="form-grid" id="eventForm" data-id="${V.esc(e.id||'')}"><div class="field full"><label>Название</label><input class="input" name="title" required value="${V.esc(e.title||'')}"></div><div class="field"><label>Тип</label><select class="select" name="type">${[['competition','Соревнования'],['camp','Лагерь'],['gathering','Сборы'],['holiday','Праздник'],['meeting','Собрание'],['other','Другое']].map(([k,v])=>`<option value="${k}" ${(e.type||'other')===k?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label>Дата</label><input class="input" type="date" name="date" required value="${V.esc(e.date||monthStart(ui.month))}"></div><div class="field"><label>Время</label><input class="input" name="time" value="${V.esc(e.time||'')}"></div><div class="field"><label>Ответственный</label><select class="select" name="ownerId">${optionsUsers(e.ownerId||C.currentUser().id)}</select></div><div class="field full"><label>Место</label><input class="input" name="location" value="${V.esc(e.location||'')}"></div><div class="field"><label>План участников</label><input class="input" type="number" name="planParticipants" min="0" value="${Number(e.planParticipants||0)}"></div><div class="field"><label>Факт участников</label><input class="input" type="number" name="factParticipants" min="0" value="${Number(e.factParticipants||0)}"></div><div class="field"><label>План выручки</label><input class="input" type="number" name="planRevenue" min="0" value="${Number(e.planRevenue||0)}"></div><div class="field"><label>Факт выручки</label><input class="input" type="number" name="factRevenue" min="0" value="${Number(e.factRevenue||0)}"></div><div class="form-actions"><button type="button" class="btn btn-ghost" data-action="closeModal">Отмена</button><button class="btn btn-primary">Сохранить мероприятие</button></div></form>`}
function goalForm(goal=null){const g=goal||{};return `<form class="form-grid" id="goalForm" data-id="${V.esc(g.id||'')}"><div class="field full"><label>Цель</label><input class="input" name="title" required value="${V.esc(g.title||'')}"></div><div class="field"><label>Автоматический показатель</label><select class="select" name="metric">${[['revenue','Выручка'],['occupancy','Загрузка групп'],['conversion','Конверсия'],['renewal','Продления'],['taskCompletion','Выполнение задач'],['events','Количество мероприятий'],['students','Количество детей'],['custom','Ручной показатель']].map(([k,v])=>`<option value="${k}" ${(g.metric||'occupancy')===k?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label>Период</label><select class="select" name="month"><option value="all" ${(g.month||'all')==='all'?'selected':''}>Каждый месяц</option>${Object.keys(C.getState().months).sort().map(k=>`<option value="${k}" ${g.month===k?'selected':''}>${C.monthLabel(k)}</option>`).join('')}</select></div><div class="field"><label>План</label><input class="input" type="number" name="target" min="0" value="${Number(g.target||0)}"></div><div class="field"><label>Единица</label><input class="input" name="unit" value="${V.esc(g.unit||'%')}"></div><div class="field"><label>Ответственный</label><select class="select" name="ownerId">${optionsUsers(g.ownerId||'sofa')}</select></div><div class="field"><label>Ручной факт (только custom)</label><input class="input" type="number" name="manualFact" value="${Number(g.manualFact||0)}"></div><div class="form-actions"><button type="button" class="btn btn-ghost" data-action="closeModal">Отмена</button><button class="btn btn-primary">Сохранить цель</button></div></form>`}
function monthPlanForm(){const p=C.getState().months[ui.month]||{};return `<form class="form-grid" id="monthPlanForm"><div class="field full"><label>Месяц</label><input class="input" value="${C.monthLabel(ui.month)}" disabled></div><div class="field"><label>Минимум</label><input class="input" type="number" name="min" value="${Number(p.min||2500000)}"></div><div class="field"><label>План</label><input class="input" type="number" name="target" value="${Number(p.target||3000000)}"></div><div class="field"><label>Сильный результат</label><input class="input" type="number" name="stretch" value="${Number(p.stretch||3800000)}"></div><div class="field"><label>Ручной факт (при необходимости)</label><input class="input" type="number" name="factManual" value="${Number(p.factManual||0)}"></div><div class="field full"><label>Фокус месяца</label><textarea class="textarea" name="focus">${V.esc(p.focus||'')}</textarea></div><div class="form-actions"><button type="button" class="btn btn-ghost" data-action="closeModal">Отмена</button><button class="btn btn-primary">Сохранить план</button></div></form>`}
function quickAdd(){const role=C.effectiveRole(),cards=[];if(C.can('task.create'))cards.push(['addTask','✓','Задача','Ответственный и дедлайн']);if(C.can('sale.edit'))cards.push(['addSale','₽','Продажа','Обновит выручку и прогноз']);if(C.can('group.edit'))cards.push(['addGroup','◉','Группа','Дети, вместимость и загрузка']);if(C.can('event.edit'))cards.push(['addEvent','★','Мероприятие','Календарь, участники и факт']);if(role==='mentor'||C.can('view.allOperations'))cards.push(['addRecommendation','→','Рекомендация','Передать ребёнка администратору']);if(role==='admin'||C.can('view.allOperations'))cards.push(['addLead','◎','Лид','Пробная или продление']);openModal('Что добавить?','Данные сразу попадут в общую базу',`<div class="quick-grid">${cards.map(([a,i,t,s])=>`<button class="quick-card" data-action="${a}"><span class="metric-icon">${i}</span><b>${t}</b><small>${s}</small></button>`).join('')}</div>`,'БЫСТРОЕ ДЕЙСТВИЕ')}
function confirmDeleteTask(id){const task=C.getState().tasks.find(t=>t.id===id);if(!task||!C.can('task.delete',task)){toast('Удалять задачи могут только Роман и Софа','error');return}openModal('Удалить задачу?','Задача исчезнет у всех сотрудников, но останется в архиве',`<div class="confirm-box"><b>${V.esc(task.title)}</b><p>Удаление синхронизируется на всех устройствах. Восстановить задачу смогут Роман или Софа.</p></div><div class="form-actions" style="margin-top:16px"><button class="btn btn-ghost" data-action="closeModal">Отмена</button><button class="btn btn-danger" data-action="confirmDeleteTask" data-id="${V.esc(id)}">Удалить</button></div>`,'КОНТРОЛЬ ДОСТУПА')}
function handleAction(button){const action=button.dataset.action,id=button.dataset.id,value=button.dataset.value;
 switch(action){
  case'closeModal':closeModal();break;case'toggleSidebar':ui.sidebar=!ui.sidebar;$('#sidebar').classList.toggle('open',ui.sidebar);$('#sidebarScrim').classList.toggle('hidden',!ui.sidebar);break;case'toggleRoleMenu':$('#rolePopover').classList.toggle('hidden');break;case'previewProfile':ui.view=button.dataset.viewTarget;ui.mentorId=button.dataset.user==='ivan'?'ivan':ui.mentorId;ui.adminId=button.dataset.user==='anya'?'anya':ui.adminId;$('#rolePopover').classList.add('hidden');render();break;case'openSettings':navigate('settings');break;case'quickAdd':quickAdd();break;case'addTask':closeModal();openTask();break;case'addAdminTask':openTask(null,{ownerId:C.visible(C.getState().users).find(u=>u.role==='admin')?.id||'anya',title:'',priority:'high'});break;case'addMentorTask':openTask(null,{ownerId:C.visible(C.getState().users).find(u=>u.role==='mentor'&&u.direction===C.currentUser().direction)?.id||'ivan'});break;case'editTask':openTask(C.getState().tasks.find(t=>t.id===id));break;case'completeTask':if(C.can('task.edit',C.getState().tasks.find(t=>t.id===id)))C.commit(s=>{const t=s.tasks.find(x=>x.id===id);if(t){t.status='done';t.completedAt=new Date().toISOString();t.updatedAt=new Date().toISOString()}},'Задача выполнена',{taskId:id});break;case'deleteTask':confirmDeleteTask(id);break;case'confirmDeleteTask':if(!C.can('task.delete',C.getState().tasks.find(t=>t.id===id))){toast('Удалять задачи могут только Роман и Софа','error');return}C.commit(s=>{const t=s.tasks.find(x=>x.id===id);if(t){t.deletedAt=new Date().toISOString();t.deletedBy=C.currentUser().id;t.updatedAt=new Date().toISOString()}},'Удалена задача',{taskId:id});closeModal();toast('Задача удалена и отправлена в архив');break;case'restoreTask':if(!C.can('task.restore'))return;C.commit(s=>{const t=s.tasks.find(x=>x.id===id);if(t){t.deletedAt=null;t.deletedBy=null;t.updatedAt=new Date().toISOString()}},'Восстановлена задача',{taskId:id});break;
  case'addGroup':openGroup();break;case'editGroup':openGroup(C.getState().groups.find(g=>g.id===id));break;case'addSale':closeModal();openSale();break;case'editSale':openSale(C.getState().sales.find(s=>s.id===id));break;case'addLead':closeModal();openModal('Новый лид','Появится у администратора и в конверсии',leadForm(),'КЛИЕНТЫ');break;case'addRecommendation':closeModal();openModal('Рекомендация ребёнку','Сразу появится у выбранного администратора',recommendationForm(),'НАСТАВНИК → АДМИНИСТРАТОР');break;case'toggleRecommendation':C.commit(s=>{const r=s.recommendations.find(x=>x.id===id);if(r){r.status=r.status==='done'?'new':'done';r.updatedAt=new Date().toISOString()}},'Изменён статус рекомендации',{recommendationId:id});break;
  case'addEvent':openModal('Новое мероприятие','План, факт, участники и выручка',eventForm(),'КАЛЕНДАРЬ');break;case'editEvent':{const e=C.getState().events.find(x=>x.id===id);if(C.can('event.edit',e))openModal('Изменить мероприятие','Данные обновятся в календаре и аналитике',eventForm(e),'КАЛЕНДАРЬ');break}case'addGoal':openModal('Новая цель','Выберите показатель — факт будет считаться автоматически',goalForm(),'ПЛАН РАЗВИТИЯ');break;case'editGoal':{const g=C.getState().goals.find(x=>x.id===id);if(C.can('goal.edit',g))openModal('Изменить цель','Факт останется связан с общей базой',goalForm(g),'ПЛАН РАЗВИТИЯ');break}case'editMonthPlan':openModal('План месяца','Финансовые границы и фокус',monthPlanForm(),'УЧЕБНЫЙ ГОД');break;
  case'selectMonth':ui.month=button.dataset.month;ui.taskMode='month';render();break;case'groupDirection':ui.groupDirection=value;render();break;case'taskMode':ui.taskMode=value;render();break;case'goTasks':navigate('tasks');break;case'goCalendar':navigate('calendar');break;case'syncNow':C.syncNow().then(()=>toast('База синхронизирована')).catch(e=>toast(e.message,'error'));break;case'archiveMonth':if(!C.can('archive.create'))return;openModal(`Закрыть ${C.monthLabel(ui.month)}?`,'Снимок сохранит факт месяца и статистику команды',`<div class="confirm-box">После закрытия текущие данные продолжат меняться, а архивный снимок останется зафиксированным.</div><div class="form-actions" style="margin-top:16px"><button class="btn btn-ghost" data-action="closeModal">Отмена</button><button class="btn btn-primary" data-action="confirmArchive">Закрыть месяц</button></div>`,'АРХИВ');break;case'confirmArchive':C.archiveMonth(ui.month);closeModal();toast('Месяц сохранён в архиве');break;
  case'copyAccess':copyText(C.shareLink(button.dataset.role,button.dataset.user),'Ссылка скопирована');break;case'copySofaLink':copyText(C.shareLink('manager','sofa'),'Ссылка Софы скопирована');break;case'exportData':C.exportState();toast('Резервная копия подготовлена');break;case'importData':$('#importInput').click();break;case'retryLegacyImport':retryLegacyImport();break;
 }
}
function copyText(text,message){navigator.clipboard?.writeText(text).then(()=>toast(message)).catch(()=>{openModal('Скопируйте ссылку','',`<textarea class="textarea" style="min-height:150px">${V.esc(text)}</textarea>`,'ДОСТУП')})}
function formData(form){return Object.fromEntries(new FormData(form).entries())}
function submitForm(form){
 const data=formData(form),stamp=new Date().toISOString();
 if(form.id==='taskForm'){const id=form.dataset.id,title=data.title.trim();if(!title)return;const existing=C.getState().tasks.find(t=>t.id===id);if(existing&&!C.can('task.edit',existing)){toast('Недостаточно прав','error');return}C.commit(s=>{let t=s.tasks.find(x=>x.id===id);if(!t){t={id:C.uid('task'),createdAt:stamp,createdBy:C.currentUser().id};s.tasks.push(t)}Object.assign(t,{title,description:data.description.trim(),ownerId:data.ownerId,deadline:data.deadline,month:data.month||String(data.deadline).slice(0,7)||ui.month,priority:data.priority,status:data.status,goalId:data.goalId||null,groupId:data.groupId||null,updatedAt:stamp})},existing?'Изменена задача':'Создана задача',{taskId:id||'new',ownerId:data.ownerId,month:data.month});closeModal();toast(existing?'Задача обновлена':'Задача создана');return}
 if(form.id==='groupForm'){const id=form.dataset.id,existing=C.getState().groups.find(g=>g.id===id);if(!C.can('group.edit',existing)){toast('Недостаточно прав','error');return}C.commit(s=>{let g=s.groups.find(x=>x.id===id);if(!g){g={id:C.uid('group'),createdAt:stamp};s.groups.push(g)}Object.assign(g,{mentorId:data.mentorId,direction:data.direction,name:data.name.trim(),day:data.day,time:data.time.trim(),students:Number(data.students)||0,capacity:Math.max(1,Number(data.capacity)||8),updatedAt:stamp})},existing?'Изменена группа':'Создана группа',{groupId:id||'new',mentorId:data.mentorId});closeModal();toast('Группа сохранена; показатели пересчитаны');return}
 if(form.id==='saleForm'){if(!C.can('sale.edit'))return;const id=form.dataset.id,existing=C.getState().sales.find(x=>x.id===id);C.commit(s=>{let sale=s.sales.find(x=>x.id===id);if(!sale){sale={id:C.uid('sale'),createdAt:stamp,createdBy:C.currentUser().id};s.sales.push(sale)}Object.assign(sale,{date:data.date,adminId:data.adminId,clientName:data.clientName.trim(),type:data.type,amount:Number(data.amount)||0,note:data.note.trim(),updatedAt:stamp})},existing?'Изменена продажа':'Добавлена продажа',{saleId:id||'new',amount:Number(data.amount)||0});closeModal();toast('Продажа сохранена; прогноз обновлён');return}
 if(form.id==='leadForm'){C.commit(s=>s.leads.push({id:C.uid('lead'),date:data.date,adminId:data.adminId,clientName:data.clientName.trim(),stage:data.stage,contact:data.contact.trim(),createdAt:stamp,updatedAt:stamp}),'Добавлен лид',{adminId:data.adminId,stage:data.stage});closeModal();toast('Лид добавлен');return}
 if(form.id==='recommendationForm'){C.commit(s=>s.recommendations.push({id:C.uid('rec'),mentorId:data.mentorId,adminId:data.adminId,childName:data.childName.trim(),recommendation:data.recommendation,note:data.note.trim(),status:'new',date:today(),createdAt:stamp,updatedAt:stamp}),'Передана рекомендация',{mentorId:data.mentorId,adminId:data.adminId});closeModal();toast('Рекомендация появилась у администратора');return}
 if(form.id==='eventForm'){if(!C.can('event.edit'))return;const id=form.dataset.id,existing=C.getState().events.find(x=>x.id===id);C.commit(s=>{let e=s.events.find(x=>x.id===id);if(!e){e={id:C.uid('event'),createdAt:stamp};s.events.push(e)}Object.assign(e,{title:data.title.trim(),type:data.type,date:data.date,time:data.time.trim(),ownerId:data.ownerId,location:data.location.trim(),planParticipants:Number(data.planParticipants)||0,factParticipants:Number(data.factParticipants)||0,planRevenue:Number(data.planRevenue)||0,factRevenue:Number(data.factRevenue)||0,updatedAt:stamp})},existing?'Изменено мероприятие':'Создано мероприятие',{eventId:id||'new'});closeModal();toast('Календарь обновлён');return}
 if(form.id==='goalForm'){if(!C.can('goal.edit'))return;const id=form.dataset.id,existing=C.getState().goals.find(x=>x.id===id);C.commit(s=>{let g=s.goals.find(x=>x.id===id);if(!g){g={id:C.uid('goal'),createdAt:stamp};s.goals.push(g)}Object.assign(g,{title:data.title.trim(),metric:data.metric,month:data.month,target:Number(data.target)||0,unit:data.unit.trim(),ownerId:data.ownerId,manualFact:Number(data.manualFact)||0,updatedAt:stamp})},existing?'Изменена цель':'Создана цель',{goalId:id||'new',metric:data.metric});closeModal();toast('Цель сохранена');return}
 if(form.id==='monthPlanForm'){if(!C.can('goal.edit'))return;C.commit(s=>{s.months[ui.month]={...s.months[ui.month],min:Number(data.min)||0,target:Number(data.target)||0,stretch:Number(data.stretch)||0,factManual:Number(data.factManual)||0,focus:data.focus.trim(),updatedAt:stamp}},'Изменён план месяца',{month:ui.month});closeModal();toast('План месяца обновлён');return}
}
function bindDragDrop(){
 $$('.task-card[draggable=true]').forEach(card=>{card.addEventListener('dragstart',()=>{draggedTask=card.dataset.taskId;card.classList.add('dragging')});card.addEventListener('dragend',()=>{draggedTask=null;card.classList.remove('dragging');$$('.drop-active').forEach(x=>x.classList.remove('drop-active'))})});
 $$('[data-drop-status]').forEach(col=>{col.addEventListener('dragover',e=>{if(!draggedTask)return;e.preventDefault();col.parentElement.classList.add('drop-active')});col.addEventListener('dragleave',()=>col.parentElement.classList.remove('drop-active'));col.addEventListener('drop',e=>{e.preventDefault();const task=C.getState().tasks.find(t=>t.id===draggedTask),status=col.dataset.dropStatus;if(task&&C.can('task.edit',task))C.commit(s=>{const t=s.tasks.find(x=>x.id===draggedTask);if(t){t.status=status;t.updatedAt=new Date().toISOString();if(status==='done')t.completedAt=new Date().toISOString()}},'Перемещена задача',{taskId:draggedTask,status});draggedTask=null})})
}
async function retryLegacyImport(){
 if(!C.can('view.allOperations')&&C.effectiveRole()!=='owner'){toast('Импорт доступен Роману и Софе','error');return}openModal('Импорт старой базы','Открываем Growth OS 6.0 в защищённом скрытом окне',`<div class="empty"><b>Подключение к старой базе…</b><span>Не закрывайте окно несколько секунд.</span></div>`,'МИГРАЦИЯ');
 try{const legacy=await new Promise((resolve,reject)=>{const frame=document.createElement('iframe');frame.style.cssText='position:fixed;width:1px;height:1px;opacity:0;left:-9999px';let timer=setTimeout(()=>{frame.remove();reject(new Error('Старая база не ответила'))},15000);frame.onload=()=>{let n=0,p=setInterval(()=>{n++;try{const api=frame.contentWindow?.EKGrowthOS;if(api?.getState){clearInterval(p);clearTimeout(timer);const value=api.getState();frame.remove();resolve(value)}}catch{}if(n>120){clearInterval(p);clearTimeout(timer);frame.remove();reject(new Error('Не удалось прочитать старую базу'))}},100)};frame.src=`/legacy/index.html${location.search}${location.hash}`;document.body.appendChild(frame)});const migrated=C.normalizeLegacy(legacy);C.commit(s=>{const merged=C.mergeState(s,migrated);for(const key of Object.keys(merged))s[key]=merged[key];s.meta.legacyStatus='manual-import'},'Повторный импорт старой базы',{});closeModal();toast('Старая база импортирована и объединена')}
 catch(error){closeModal();toast(error.message,'error')}
}
function globalEvents(){
 document.addEventListener('click',event=>{const viewBtn=event.target.closest('[data-view]');if(viewBtn){navigate(viewBtn.dataset.view);return}const actionBtn=event.target.closest('[data-action]');if(actionBtn){event.preventDefault();handleAction(actionBtn)}});
 document.addEventListener('submit',event=>{if(event.target.matches('form')){event.preventDefault();submitForm(event.target)}});
 $('#monthSelect').addEventListener('change',event=>{ui.month=event.target.value;ui.taskMode='month';ui.taskOwner='all';ui.taskPriority='all';render()});
 document.addEventListener('input',event=>{if(event.target.id==='taskSearch'){ui.taskSearch=event.target.value;clearTimeout(event.target.__timer);event.target.__timer=setTimeout(render,180)}if(event.target.id==='groupSearch'){ui.groupSearch=event.target.value;clearTimeout(event.target.__timer);event.target.__timer=setTimeout(render,180)}});
 document.addEventListener('change',event=>{if(event.target.id==='taskOwner'){ui.taskOwner=event.target.value;render()}if(event.target.id==='taskPriority'){ui.taskPriority=event.target.value;render()}if(event.target.id==='groupMentor'){ui.groupMentor=event.target.value;render()}});
 $('#importInput').addEventListener('change',async event=>{const file=event.target.files?.[0];if(!file)return;try{await C.importState(file);toast('Резервная копия импортирована')}catch(error){toast('Ошибка импорта: '+error.message,'error')}event.target.value=''});
 $('#modal').addEventListener('click',event=>{if(event.target.id==='modal')closeModal()});addEventListener('keydown',event=>{if(event.key==='Escape'){closeModal();$('#rolePopover').classList.add('hidden')}});
 document.addEventListener('ek61:sync',event=>{const {status,message}=event.detail||{},dot=$('#syncDot'),spinner=$('#syncSpinner');dot.className=`sync-dot ${status==='busy'?'busy':status==='off'?'off':''}`;spinner.classList.toggle('busy',status==='busy');$('#syncTitle').textContent=status==='busy'?'Синхронизация…':status==='off'?'Локальный режим':'Общая база активна';$('#syncSubtitle').textContent=message||''});
}
async function start(){
 globalEvents();try{$('#bootText').textContent='Загружаем роли и общую базу…';await C.init();C.setRenderer(render);ensureView();render();$('#appShell').classList.remove('hidden');setTimeout(()=>{$('#boot').classList.add('fade');setTimeout(()=>$('#boot').classList.add('hidden'),500)},250)}catch(error){console.error(error);$('#bootText').textContent='Не удалось запустить систему';$('#bootSub').textContent=error.message;$('#bootRetry').classList.remove('hidden');$('#bootRetry').onclick=()=>location.reload()}}
start();
})();
