(()=>{
'use strict';
const C=window.EK61;
const esc=value=>String(value??'').replace(/[&<>"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[ch]));
const attr=esc;
const fmtDate=value=>{if(!value)return'—';const d=new Date(value);return Number.isNaN(d.getTime())?esc(value):d.toLocaleDateString('ru-RU',{day:'2-digit',month:'short',year:'numeric'})};
const fmtShort=value=>{if(!value)return'—';const d=new Date(value);return Number.isNaN(d.getTime())?esc(value):d.toLocaleDateString('ru-RU',{day:'2-digit',month:'short'})};
const user=id=>C.findUser(id)||{id,name:id||'Не назначено',short:'—',role:'team',title:''};
const dirName=value=>({rollers:'Ролики',bike:'ВЕЛО / BMX',skate:'Скейт',sales:'Продажи',all:'Весь клуб'}[value]||value||'—');
const typeName=value=>({competition:'Соревнования',camp:'Лагерь',gathering:'Сборы',holiday:'Праздник',meeting:'Собрание',other:'Другое'}[value]||value||'Другое');
const saleType=value=>({subscription:'Абонемент',renewal:'Продление',trial:'Пробная',event:'Мероприятие',camp:'Лагерь',individual:'Индивидуальная',other:'Другое'}[value]||value||'Продажа');
const goalUnit=g=>g.metric==='revenue'?'₽':(g.unit||(['occupancy','conversion','renewal','taskCompletion'].includes(g.metric)?'%':''));
const pageMeta={
 dashboard:['Главная Романа','Стратегический штаб собственника'],manager:['Кабинет Софы','Управление командой, администраторами и результатом клуба'],year:['Учебный год','План, факт и фокус каждого месяца 2026/27'],groups:['Группы и загрузка','Живые показатели наставников, мест и направлений'],goals:['План развития','Цели обновляются автоматически из задач, продаж, групп и мероприятий'],tasks:['Задачи','Задачи выбранного месяца, ответственные и контроль исполнения'],calendar:['Календарь','Мероприятия, соревнования, сборы, лагерь и дедлайны'],analytics:['Аналитика и прогноз','Диаграммы, сценарии и прогноз результата при текущем темпе'],archive:['Архив','Закрытые месяцы, история показателей и удалённые задачи'],stas:['Кабинет Стаса','Роллер-направление, наставники, загрузка и задачи'],mentor:['Кабинет наставника','Свои группы, дети, задачи и рекомендации'],admin:['Кабинет администратора','Продажи, клиенты, продления и задачи'],team:['Командный экран','Общие цели, события и результат без закрытых данных'],settings:['Настройки','Доступы, синхронизация, роли и резервные копии']
};
function head(title,description,actions=''){return `<div class="page-head"><div><div class="eyebrow">${esc(C.monthLabel(window.EK61_APP?.ui?.month||C.monthKey()))}</div><h2>${esc(title)}</h2><p>${esc(description||'')}</p></div>${actions?`<div class="head-actions">${actions}</div>`:''}</div>`}
function button(label,action,kind='btn-ghost',extra=''){return `<button class="btn ${kind}" data-action="${attr(action)}" ${extra}>${label}</button>`}
function metric(label,value,sub='',icon='◆',progressValue=null,classes=''){return `<article class="card metric ${classes}"><div class="metric-icon">${icon}</div><div class="metric-label">${esc(label)}</div><div class="metric-value">${value}</div><div class="metric-sub">${esc(sub)}</div>${progressValue===null?'':progress(progressValue)}</article>`}
function progress(value){return `<div class="progress"><i style="width:${C.clamp(value,0,100)}%"></i></div>`}
function pill(text,kind=''){return `<span class="pill ${kind}">${esc(text)}</span>`}
function avatar(u,size=''){return `<span class="avatar ${size}">${esc(u.short||u.name?.slice(0,2)||'—')}</span>`}
function empty(title,text,action=''){return `<div class="empty"><b>${esc(title)}</b><span>${esc(text)}</span>${action?`<div style="margin-top:13px">${action}</div>`:''}</div>`}
function cardTitle(title,sub='',action=''){return `<div class="card-title"><div><h3>${esc(title)}</h3>${sub?`<p>${esc(sub)}</p>`:''}</div>${action}</div>`}
function roleScopeLabel(){const role=C.effectiveRole(),u=C.currentUser();return role==='owner'?'Весь клуб':role==='manager'?'Управляющая · весь клуб':role==='head'?`Направление: ${dirName(u.direction)}`:role==='mentor'?`Наставник: ${u.name}`:role==='admin'?`Администратор: ${u.name}`:'Командный экран'}
function alertRows(m){
 const items=[];
 if(m.forecast<m.plan.min)items.push({kind:'red',title:'Прогноз ниже минимальной планки',text:`При текущем темпе месяц завершится около ${C.money(m.forecast)}. Минимум — ${C.money(m.plan.min)}.`});
 else if(m.forecast<m.plan.target)items.push({kind:'',title:'До цели месяца ещё есть разрыв',text:`Прогноз ${C.money(m.forecast)}. До цели не хватает ${C.money(Math.max(0,m.plan.target-m.forecast))}.`});
 else items.push({kind:'',title:'Темп соответствует цели',text:`Базовый прогноз ${C.money(m.forecast)} при плане ${C.money(m.plan.target)}.`});
 if(m.occupancy<60)items.push({kind:'red',title:'Низкая средняя загрузка',text:`Загрузка ${C.percent(m.occupancy)}. Свободно ${m.free} мест.`});
 else if(m.occupancy<75)items.push({kind:'',title:'Есть резерв загрузки',text:`Загрузка ${C.percent(m.occupancy)}. До 75% можно добрать примерно ${Math.max(0,Math.ceil(m.capacity*.75-m.students))} детей.`});
 if(m.overdue.length)items.push({kind:'red',title:`Просрочено задач: ${m.overdue.length}`,text:'Они не смешиваются с задачами выбранного месяца, но остаются отдельным сигналом.'});
 if(!m.sales.length)items.push({kind:'',title:'Нет внесённых продаж за месяц',text:'Добавьте оплаты и продления — прогноз, цели и статистика обновятся автоматически.'});
 return items;
}
function alertsHTML(m){return `<div class="alert-list">${alertRows(m).map(x=>`<div class="alert-row ${x.kind}"><i></i><div><b>${esc(x.title)}</b><small>${esc(x.text)}</small></div></div>`).join('')}</div>`}
function taskCard(t){
 const owner=user(t.ownerId),canDelete=C.can('task.delete',t),deadline=t.deadline?fmtShort(t.deadline):'без срока',overdue=t.status!=='done'&&t.deadline&&t.deadline<new Date().toISOString().slice(0,10);
 return `<article class="task-card" draggable="${C.can('task.edit',t)?'true':'false'}" data-task-id="${attr(t.id)}">
 <div class="task-top"><h4>${esc(t.title)}</h4>${canDelete?`<button class="task-delete" data-action="deleteTask" data-id="${attr(t.id)}" title="Удалить задачу">×</button>`:''}</div>
 ${t.description?`<p>${esc(t.description)}</p>`:''}
 <div class="task-meta">${pill(owner.name)}${pill(deadline,overdue?'red':'gray')}${pill(C.PRIORITY[t.priority]||t.priority,t.priority==='critical'?'red':t.priority==='high'?'':'gray')}</div>
 <div class="task-actions"><button class="btn btn-small btn-ghost" data-action="editTask" data-id="${attr(t.id)}">Открыть</button>${t.status!=='done'&&C.can('task.edit',t)?`<button class="btn btn-small btn-soft" data-action="completeTask" data-id="${attr(t.id)}">Готово</button>`:''}</div>
 </article>`;
}
function taskListRows(tasks){return tasks.length?`<div class="simple-list">${tasks.slice(0,8).map(t=>`<div class="list-row"><div class="grow"><b>${esc(t.title)}</b><small>${esc(user(t.ownerId).name)} · ${fmtDate(t.deadline)}</small></div>${pill(C.TASK_STATUS[t.status]||t.status,t.status==='done'?'green':'')}</div>`).join('')}</div>`:empty('Задач нет','На выбранный месяц задачи ещё не добавлены')}
function eventRows(events){return events.length?`<div class="simple-list">${events.slice(0,7).map(e=>`<div class="list-row"><div class="metric-icon">${e.type==='competition'?'🏆':e.type==='camp'?'⚡':'●'}</div><div class="grow"><b>${esc(e.title)}</b><small>${fmtDate(e.date)} · ${esc(e.location||typeName(e.type))}</small></div>${pill(`${Number(e.factParticipants||0)}/${Number(e.planParticipants||0)} чел.`)}</div>`).join('')}</div>`:empty('Событий нет','В выбранном месяце пока нет мероприятий',C.can('event.edit')?button('+ Мероприятие','addEvent','btn-primary'):'')}
function mentorTable(stats){
 return `<div class="table-wrap"><table class="data-table"><thead><tr><th>Наставник</th><th>Направление</th><th>Группы</th><th>Дети / места</th><th>Загрузка</th><th>Задачи</th><th>Рекомендации</th></tr></thead><tbody>${stats.map(x=>`<tr><td><span class="strong">${esc(x.user.name)}</span><br><small>${esc(x.user.title)}</small></td><td>${esc(dirName(x.user.direction))}</td><td>${x.groups.length}</td><td>${x.students} / ${x.capacity}<br><small>свободно ${x.free}</small></td><td class="load-cell"><div class="load-line"><b>${C.percent(x.occupancy)}</b><small>${x.occupancy>=75?'норма':x.occupancy>=60?'рост':'приоритет'}</small></div><div class="mini-progress"><i style="width:${C.clamp(x.occupancy,0,100)}%"></i></div></td><td>${x.done}/${x.tasks.length}</td><td>${x.recommendations}</td></tr>`).join('')}</tbody></table></div>`
}
function ownerDashboard(ctx){
 const m=ctx.metrics,priorities=m.tasks.filter(t=>t.status!=='done').sort((a,b)=>(b.priority==='critical')-(a.priority==='critical')||String(a.deadline).localeCompare(String(b.deadline))).slice(0,6);
 return `<div class="page">${head('Штаб клуба',`Все показатели за ${C.monthLabel(ctx.month)} пересчитываются из общей базы`,button('+ Продажа','addSale','btn-primary')+button('+ Задача','addTask'))}
 <section class="grid grid-2"><article class="card hero"><div class="eyebrow">ВЫРУЧКА И ПРОГНОЗ</div><div class="hero-value">${C.money(m.revenue)}</div><div class="hero-copy">План ${C.money(m.plan.target)} · минимум ${C.money(m.plan.min)} · текущий прогноз ${C.money(m.forecast)}</div>${progress(m.plan.target?m.revenue/m.plan.target*100:0)}<div class="forecast-grid"><div class="forecast-box"><small>Минимум</small><b>${C.money(m.plan.min)}</b></div><div class="forecast-box active"><small>План</small><b>${C.money(m.plan.target)}</b></div><div class="forecast-box"><small>Сильный</small><b>${C.money(m.plan.stretch)}</b></div><div class="forecast-box"><small>Прогноз</small><b>${C.money(m.forecast)}</b></div></div></article>
 <article class="card">${cardTitle('Сигналы собственника','Что требует решения сейчас')}${alertsHTML(m)}</article></section>
 <section class="grid grid-5">${metric('Загрузка групп',C.percent(m.occupancy),`${m.students} детей · ${m.free} свободных мест`,'◉',m.occupancy)}${metric('Задачи месяца',`${m.doneTasks}/${m.tasks.length}`,`${m.overdue.length} просрочено`,'✓',m.taskCompletion)}${metric('Продажи',m.sales.length,`${C.money(m.revenue)} внесено в базу`,'₽')}${metric('Мероприятия',m.events.length,`${m.events.reduce((s,e)=>s+Number(e.factParticipants||0),0)} участников`,'★')}${metric('Конверсия',C.percent(m.conversion),`${m.trials} пробных · ${m.paid} оплат`,'↗',m.conversion)}</section>
 <section class="grid grid-2"><article class="card">${cardTitle('Главные задачи месяца','Фильтр строго по выбранному месяцу',button('Все задачи','goTasks','btn-small btn-ghost'))}${taskListRows(priorities)}</article><article class="card">${cardTitle('Ближайшие события','Календарь автоматически меняется вместе с месяцем',button('Календарь','goCalendar','btn-small btn-ghost'))}${eventRows(m.events)}</article></section>
 <article class="card">${cardTitle('Наставники и загрузка','Изменение группы у наставника сразу пересчитывает руководителя и управляющую')}${mentorTable(m.mentorStats)}</article>
 <article class="card">${cardTitle('Как обновляются показатели','Одна общая база без ручного дублирования')}<div class="source-flow"><span class="source-node">Наставник обновил группу</span><span class="source-arrow">→</span><span class="source-node">Загрузка направления</span><span class="source-arrow">→</span><span class="source-node">Кабинет Стаса</span><span class="source-arrow">→</span><span class="source-node">Кабинет Софы</span><span class="source-arrow">→</span><span class="source-node">Штаб Романа</span></div></article></div>`;
}
function managerDashboard(ctx){
 const m=ctx.metrics,adminTasks=m.tasks.filter(t=>user(t.ownerId).role==='admin'),mentorRisks=m.mentorStats.filter(x=>x.occupancy<60);
 return `<div class="page">${head('Кабинет Софы',`Операционное управление клубом за ${C.monthLabel(ctx.month)}`,button('+ Задача админу','addAdminTask','btn-primary')+button('+ Продажа','addSale'))}
 <article class="card hero"><div class="profile-hero">${avatar(user('sofa'))}<div><div class="eyebrow">УПРАВЛЯЮЩАЯ КЛУБОМ</div><h2>Софа</h2><p>Ставит задачи администраторам, контролирует продажи, продления, наставников и выполнение плана.</p></div></div><div class="status-row">${pill(`План ${C.money(m.plan.target)}`,'big')}${pill(`Прогноз ${C.money(m.forecast)}`,'big')}${pill(`Загрузка ${C.percent(m.occupancy)}`,'big')}${pill(`Просрочено ${m.overdue.length}`,m.overdue.length?'red':'green')}</div></article>
 <section class="grid grid-5">${metric('Выручка',C.money(m.revenue),`прогноз ${C.money(m.forecast)}`,'₽',m.plan.target?m.revenue/m.plan.target*100:0)}${metric('Задачи админов',`${adminTasks.filter(t=>t.status==='done').length}/${adminTasks.length}`,`за ${C.monthLabel(ctx.month)}`,'✓',adminTasks.length?adminTasks.filter(t=>t.status==='done').length/adminTasks.length*100:0)}${metric('Продления',m.renewals,`результат ${C.percent(m.renewal)}`,'↻',m.renewal)}${metric('Конверсия',C.percent(m.conversion),`${m.trials} пробных`,'↗',m.conversion)}${metric('Группы риска',mentorRisks.length,mentorRisks.length?'загрузка ниже 60%':'все выше 60%','!')}</section>
 <section class="grid grid-2"><article class="card">${cardTitle('Администраторы','Продажи, лиды и текущие задачи')}${m.adminStats.length?`<div class="simple-list">${m.adminStats.map(x=>`<div class="list-row"><div>${avatar(x.user,'small')}</div><div class="grow"><b>${esc(x.user.name)}</b><small>${x.sales} продаж · ${x.leads} лидов · ${x.renewals} продлений</small></div><b>${C.money(x.revenue)}</b></div>`).join('')}</div>`:empty('Нет администраторов','Добавьте сотрудников в настройках')}</article><article class="card">${cardTitle('Красные сигналы','Автоматический контроль управляющей')}${alertsHTML(m)}</article></section>
 <article class="card">${cardTitle('Наставники','Данные подтягиваются из их личных кабинетов')}${mentorTable(m.mentorStats)}</article>
 <section class="grid grid-2"><article class="card">${cardTitle('Задачи администраторов','Софа может создавать, проверять и удалять задачи')}${taskListRows(adminTasks)}</article><article class="card">${cardTitle('Рекомендации наставников','Следующий продукт для ребёнка появляется у админов')}${recommendationRows(ctx.month)}</article></section>
 <article class="card">${cardTitle('Сайт управляющей','Старый рабочий интерфейс сохранён; Growth OS использует общий профиль и общую базу')}<div class="head-actions"><a class="btn btn-ghost" href="https://extreme-kids-troparevo-control.vercel.app/" target="_blank" rel="noopener">Открыть текущий сайт Софы</a>${button('Скопировать новую ссылку Софы','copySofaLink','btn-primary')}</div></article></div>`;
}
function recommendationRows(month){const rows=C.visible(C.getState().recommendations).filter(r=>String(r.date||r.createdAt||'').slice(0,7)===month);return rows.length?`<div class="simple-list">${rows.slice(0,8).map(r=>`<div class="list-row"><div class="grow"><b>${esc(r.childName||'Ученик')} · ${esc(r.recommendation||r.product||'Рекомендация')}</b><small>${esc(user(r.mentorId).name)} → ${esc(user(r.adminId).name)} · ${fmtDate(r.date||r.createdAt)}</small></div>${pill(r.status==='done'?'Закрыто':'В работу',r.status==='done'?'green':'')}</div>`).join('')}</div>`:empty('Рекомендаций пока нет','Наставник может передать рекомендацию администратору из своего кабинета')}
function headDashboard(ctx){
 const m=ctx.metrics,u=user('stas'),own=m.mentorStats.filter(x=>x.user.direction==='rollers'),tasks=m.tasks.filter(t=>t.ownerId==='stas'||user(t.ownerId).direction==='rollers');
 return `<div class="page">${head('Кабинет Стаса','Всё роллер-направление в одном экране',button('+ Задача наставнику','addMentorTask','btn-primary'))}<article class="card hero"><div class="profile-hero">${avatar(u)}<div><div class="eyebrow">РУКОВОДИТЕЛЬ РОЛЛЕР-НАПРАВЛЕНИЯ</div><h2>${esc(u.name)}</h2><p>Загрузка наставников, свободные места, задачи, рекомендации и качество работы.</p></div></div></article>
 <section class="grid grid-4">${metric('Дети на роликах',own.reduce((s,x)=>s+x.students,0),`${own.reduce((s,x)=>s+x.free,0)} свободных мест`,'◉')}${metric('Загрузка направления',C.percent(avg(own.map(x=>x.occupancy))),`${own.length} наставников`,'↗',avg(own.map(x=>x.occupancy)))}${metric('Задачи направления',`${tasks.filter(t=>t.status==='done').length}/${tasks.length}`,`${tasks.filter(t=>t.status!=='done'&&t.deadline&&t.deadline<new Date().toISOString().slice(0,10)).length} просрочено`,'✓',tasks.length?tasks.filter(t=>t.status==='done').length/tasks.length*100:0)}${metric('Рекомендации',own.reduce((s,x)=>s+x.recommendations,0),'передано администраторам','→')}</section>
 <article class="card">${cardTitle('Команда роллер-направления','Любое изменение в группе сразу меняет итог направления')}${mentorTable(own)}</article><section class="grid grid-2"><article class="card">${cardTitle('Задачи направления','Только выбранный месяц')}${taskListRows(tasks)}</article><article class="card">${cardTitle('Приоритеты по загрузке','Группы с наибольшим количеством свободных мест')}${weakGroups('rollers')}</article></section></div>`;
}
function avg(values){return values.length?values.reduce((a,b)=>a+Number(b||0),0)/values.length:0}
function weakGroups(direction){const groups=C.visible(C.getState().groups).filter(g=>!direction||g.direction===direction).sort((a,b)=>(Number(b.capacity)-Number(b.students))-(Number(a.capacity)-Number(a.students))).slice(0,8);return groups.length?`<div class="simple-list">${groups.map(g=>`<div class="list-row"><div class="grow"><b>${esc(user(g.mentorId).name)} · ${esc(g.name)}</b><small>${esc(g.day)} ${esc(g.time)}</small></div>${pill(`${g.students}/${g.capacity} · свободно ${Math.max(0,g.capacity-g.students)}`,g.capacity&&g.students/g.capacity>=.75?'green':'')}</div>`).join('')}</div>`:empty('Нет групп','Добавьте группы в разделе загрузки')}
function mentorDashboard(ctx){
 const actual=C.currentUser(),selectedId=ctx.ui.mentorId&&C.can('view.allOperations')?ctx.ui.mentorId:actual.id,u=user(selectedId),stats=ctx.metrics.mentorStats.find(x=>x.user.id===u.id)||{groups:[],capacity:0,students:0,free:0,occupancy:0,tasks:[],done:0,recommendations:0};
 return `<div class="page">${head(`Кабинет наставника · ${u.name}`,'Группы, дети, задачи и рекомендации в общей системе',button('+ Рекомендация','addRecommendation','btn-primary')+button('+ Задача','addTask'))}<article class="card hero"><div class="profile-hero">${avatar(u)}<div><div class="eyebrow">${esc(dirName(u.direction))}</div><h2>${esc(u.name)}</h2><p>${esc(u.title)}</p></div></div></article>
 <section class="grid grid-4">${metric('Мои группы',stats.groups.length,`${stats.students} детей`,'◉')}${metric('Загрузка',C.percent(stats.occupancy),`${stats.free} свободных мест`,'↗',stats.occupancy)}${metric('Задачи',`${stats.done}/${stats.tasks.length}`,'за выбранный месяц','✓',stats.tasks.length?stats.done/stats.tasks.length*100:0)}${metric('Рекомендации',stats.recommendations,'передано администраторам','→')}</section>
 <article class="card">${cardTitle('Мои группы','Измените детей или вместимость — показатели обновятся у Стаса, Софы и Романа')}${groupTable(stats.groups)}</article><section class="grid grid-2"><article class="card">${cardTitle('Мои задачи','Фильтр по рабочему месяцу')}${taskListRows(stats.tasks)}</article><article class="card">${cardTitle('Мои рекомендации','Что предложить детям дальше')}${recommendationRowsForMentor(u.id,ctx.month)}</article></section></div>`;
}
function recommendationRowsForMentor(id,month){const rows=C.visible(C.getState().recommendations).filter(r=>r.mentorId===id&&String(r.date||r.createdAt||'').slice(0,7)===month);return rows.length?`<div class="simple-list">${rows.map(r=>`<div class="list-row"><div class="grow"><b>${esc(r.childName)} · ${esc(r.recommendation)}</b><small>Администратор: ${esc(user(r.adminId).name)}</small></div>${pill(r.status==='done'?'Закрыто':'Передано',r.status==='done'?'green':'')}</div>`).join('')}</div>`:empty('Рекомендаций нет','Передайте администратору ребёнка на БАЗА+, второе занятие, спорт-группу или индивидуальную')}
function adminDashboard(ctx){
 const actual=C.currentUser(),selectedId=ctx.ui.adminId&&C.can('view.allOperations')?ctx.ui.adminId:actual.id,u=user(selectedId),stats=ctx.metrics.adminStats.find(x=>x.user.id===u.id)||{revenue:0,sales:0,leads:0,renewals:0,tasks:[]},recs=C.visible(C.getState().recommendations).filter(r=>(r.adminId===u.id||!r.adminId)&&String(r.date||r.createdAt||'').slice(0,7)===ctx.month);
 return `<div class="page">${head(`Кабинет администратора · ${u.name}`,'Продажи, клиенты, рекомендации наставников и задачи',button('+ Продажа','addSale','btn-primary')+button('+ Лид','addLead'))}<article class="card hero"><div class="profile-hero">${avatar(u)}<div><div class="eyebrow">АДМИНИСТРАТОР</div><h2>${esc(u.name)}</h2><p>Ведёт клиента к следующему шагу и фиксирует результат в общей базе.</p></div></div></article>
 <section class="grid grid-4">${metric('Выручка',C.money(stats.revenue),`${stats.sales} продаж`,'₽')}${metric('Лиды',stats.leads,'за выбранный месяц','◎')}${metric('Продления',stats.renewals,'зафиксировано в базе','↻')}${metric('Задачи',`${stats.tasks.filter(t=>t.status==='done').length}/${stats.tasks.length}`,'от Софы и руководителей','✓',stats.tasks.length?stats.tasks.filter(t=>t.status==='done').length/stats.tasks.length*100:0)}</section>
 <section class="grid grid-2"><article class="card">${cardTitle('Рекомендации наставников','Кому предложить следующий продукт')}${recs.length?`<div class="simple-list">${recs.map(r=>`<div class="list-row"><div class="grow"><b>${esc(r.childName)} · ${esc(r.recommendation)}</b><small>${esc(user(r.mentorId).name)} · ${fmtDate(r.date||r.createdAt)}</small></div><button class="btn btn-small ${r.status==='done'?'btn-ghost':'btn-soft'}" data-action="toggleRecommendation" data-id="${attr(r.id)}">${r.status==='done'?'Вернуть':'Закрыть'}</button></div>`).join('')}</div>`:empty('Нет рекомендаций','Новые рекомендации наставников появятся здесь автоматически')}</article><article class="card">${cardTitle('Мои задачи','Только задачи выбранного месяца')}${taskListRows(stats.tasks)}</article></section>
 <article class="card">${cardTitle('Мои продажи','Каждая запись обновляет выручку, прогноз, цели Софы и штаб Романа')}${salesTable(ctx.month,u.id)}</article></div>`;
}
function teamDashboard(ctx){const m=ctx.metrics;return `<div class="page">${head('Командный экран','Общие цели и события без закрытых данных')}<article class="card hero"><div class="eyebrow">РЕЗУЛЬТАТ КОМАНДЫ</div><div class="hero-value">${C.percent(m.occupancy)}</div><div class="hero-copy">Средняя загрузка клуба · ${m.students} спортсменов · ${m.free} свободных мест</div>${progress(m.occupancy)}</article><section class="grid grid-4">${metric('Задачи выполнены',C.percent(m.taskCompletion),`${m.doneTasks}/${m.tasks.length}`,'✓',m.taskCompletion)}${metric('События месяца',m.events.length,'соревнования, сборы и праздники','★')}${metric('Участники событий',m.events.reduce((s,e)=>s+Number(e.factParticipants||0),0),'факт за месяц','◉')}${metric('Рекомендации',C.visible(C.getState().recommendations).filter(r=>String(r.date||r.createdAt||'').slice(0,7)===ctx.month).length,'детям на следующий уровень','→')}</section><article class="card">${cardTitle('События команды','Что ждёт клуб в этом месяце')}${eventRows(m.events)}</article><article class="card">${cardTitle('Цели месяца','Публичная часть плана')}${goalCards(m.goals.filter(g=>g.metric!=='revenue'))}</article></div>`}
function yearView(ctx){
 const months=Object.entries(C.getState().months||{}).sort(([a],[b])=>a.localeCompare(b));
 return `<div class="page">${head('Учебный год 2026/27','План, факт, прогноз и фокус каждого месяца',C.can('goal.edit')?button('Настроить план','editMonthPlan','btn-primary'):'')}<div class="month-grid">${months.map(([key,p])=>{const archive=C.visible(C.getState().archives).find(a=>a.month===key),fact=archive?.revenue||(key===ctx.month?ctx.metrics.revenue:Number(p.factManual||0)),prog=p.target?fact/p.target*100:0;return `<article class="month-card ${key===ctx.month?'current':''}" data-action="selectMonth" data-month="${key}"><div class="month-name"><b>${esc(C.monthLabel(key))}</b>${key===ctx.month?pill('Сейчас'):archive?pill('Закрыт','green'):''}</div><p style="color:var(--muted);min-height:36px">${esc(p.focus||'')}</p><div class="month-values"><div><small>Минимум</small><b>${C.money(p.min)}</b></div><div><small>План</small><b>${C.money(p.target)}</b></div><div><small>Сильный</small><b>${C.money(p.stretch)}</b></div></div><div class="metric-label">Факт ${C.money(fact)}</div>${progress(prog)}</article>`}).join('')}</div></div>`;
}
function groupTable(groups){return groups.length?`<div class="table-wrap"><table class="data-table"><thead><tr><th>Наставник</th><th>Направление</th><th>Группа</th><th>День и время</th><th>Дети</th><th>Вместимость</th><th>Загрузка</th><th></th></tr></thead><tbody>${groups.map(g=>{const load=g.capacity?g.students/g.capacity*100:0;return `<tr><td><span class="strong">${esc(user(g.mentorId).name)}</span></td><td>${esc(dirName(g.direction))}</td><td><span class="strong">${esc(g.name)}</span></td><td>${esc(g.day)}<br><small>${esc(g.time)}</small></td><td>${Number(g.students||0)}</td><td>${Number(g.capacity||0)}</td><td class="load-cell"><div class="load-line"><b>${C.percent(load)}</b><small>свободно ${Math.max(0,Number(g.capacity||0)-Number(g.students||0))}</small></div><div class="mini-progress"><i style="width:${C.clamp(load,0,100)}%"></i></div></td><td>${C.can('group.edit',g)?`<button class="btn btn-small btn-ghost" data-action="editGroup" data-id="${attr(g.id)}">Изменить</button>`:''}</td></tr>`}).join('')}</tbody></table></div>`:empty('Группы не найдены','Измените фильтр или добавьте новую группу')}
function groupsView(ctx){
 const all=C.scopedGroups(),q=(ctx.ui.groupSearch||'').toLowerCase(),dir=ctx.ui.groupDirection||'all',mentor=ctx.ui.groupMentor||'all';let rows=all.filter(g=>(dir==='all'||g.direction===dir)&&(mentor==='all'||g.mentorId===mentor)&&(!q||`${g.name} ${g.day} ${g.time} ${user(g.mentorId).name}`.toLowerCase().includes(q)));
 return `<div class="page">${head('Группы и загрузка',`${roleScopeLabel()} · данные меняются в реальном времени`,C.can('group.edit')?button('+ Группа','addGroup','btn-primary'):'')}<div class="filters"><input class="input search" id="groupSearch" placeholder="Поиск группы или наставника" value="${attr(ctx.ui.groupSearch||'')}"><button class="filter-chip ${dir==='all'?'active':''}" data-action="groupDirection" data-value="all">Все</button><button class="filter-chip ${dir==='rollers'?'active':''}" data-action="groupDirection" data-value="rollers">Ролики</button><button class="filter-chip ${dir==='bike'?'active':''}" data-action="groupDirection" data-value="bike">ВЕЛО / BMX</button><button class="filter-chip ${dir==='skate'?'active':''}" data-action="groupDirection" data-value="skate">Скейт</button><select class="select compact" id="groupMentor"><option value="all">Все наставники</option>${C.scopedUsers().filter(u=>u.role==='mentor'||u.role==='head').map(u=>`<option value="${attr(u.id)}" ${mentor===u.id?'selected':''}>${esc(u.name)}</option>`).join('')}</select></div><section class="grid grid-4">${metric('Группы',rows.length,'после фильтра','◉')}${metric('Спортсмены',rows.reduce((s,g)=>s+Number(g.students||0),0),'в выбранных группах','●')}${metric('Свободные места',rows.reduce((s,g)=>s+Math.max(0,Number(g.capacity||0)-Number(g.students||0)),0),'приоритет продаж','↗')}${metric('Средняя загрузка',C.percent(avg(rows.map(g=>g.capacity?g.students/g.capacity*100:0))),'обновляется автоматически','%',avg(rows.map(g=>g.capacity?g.students/g.capacity*100:0)))}</section><article class="card">${cardTitle('Живая таблица загрузки','Наставник → руководитель → управляющая → собственник')}${groupTable(rows)}</article></div>`;
}
function goalCards(goals){return goals.length?`<div class="grid grid-3">${goals.map(g=>`<article class="card goal-card"><div class="goal-top"><div><div class="eyebrow">${esc(g.metric)}</div><div class="goal-title">${esc(g.title)}</div></div>${C.can('goal.edit')?`<button class="icon-btn" data-action="editGoal" data-id="${attr(g.id)}">⋯</button>`:''}</div><div><span class="goal-value">${g.metric==='revenue'?C.money(g.fact):`${Math.round(g.fact)}${goalUnit(g)}`}</span> <span style="color:var(--muted)">из ${g.metric==='revenue'?C.money(g.target):`${Math.round(g.target)}${goalUnit(g)}`}</span></div>${progress(g.progress)}<div class="goal-source">Источник: <b>${esc(goalSource(g.metric))}</b>. Факт не дублируется вручную.</div></article>`).join('')}</div>`:empty('Цели не заданы','Добавьте цель и выберите автоматический показатель')}
function goalSource(metric){return {revenue:'продажи и оплаты',occupancy:'группы наставников',conversion:'пробные и оплаты',renewal:'лиды на продление и продажи',taskCompletion:'задачи выбранного месяца',events:'календарь мероприятий',students:'загрузка групп',custom:'ручной показатель'}[metric]||'общая база'}
function goalsView(ctx){return `<div class="page">${head('План развития','Факт каждой цели рассчитывается из первичных данных',C.can('goal.edit')?button('+ Цель','addGoal','btn-primary'):'')}<article class="card">${cardTitle('Автоматическая связка целей','Изменили продажу, группу, задачу или событие — цель обновилась без второго ввода')}<div class="source-flow"><span class="source-node">Продажи / группы / задачи / события</span><span class="source-arrow">→</span><span class="source-node">Единые метрики месяца</span><span class="source-arrow">→</span><span class="source-node">План развития</span><span class="source-arrow">→</span><span class="source-node">Роман + Софа + руководитель</span></div></article>${goalCards(ctx.metrics.goals)}</div>`}
function tasksView(ctx){
 const mode=ctx.ui.taskMode||'month',tasks=C.scopedTasks(ctx.month,mode),owners=C.scopedUsers();
 const ownerFilter=ctx.ui.taskOwner||'all',priority=ctx.ui.taskPriority||'all',query=(ctx.ui.taskSearch||'').toLowerCase();let filtered=tasks.filter(t=>(ownerFilter==='all'||t.ownerId===ownerFilter)&&(priority==='all'||t.priority===priority)&&(!query||`${t.title} ${t.description} ${user(t.ownerId).name}`.toLowerCase().includes(query)));
 return `<div class="page">${head(`Задачи · ${C.monthLabel(ctx.month)}`,'При смене месяца канбан показывает только задачи выбранного месяца',C.can('task.create')?button('+ Задача','addTask','btn-primary'):'')}${ctx.metrics.overdue.length?`<div class="overdue-banner"><div><b>Просроченные задачи не смешиваются с текущим месяцем</b><div>${ctx.metrics.overdue.length} задач из предыдущих месяцев требуют внимания.</div></div><button class="btn btn-small btn-danger" data-action="taskMode" data-value="overdue">Показать</button></div>`:''}<div class="filters"><button class="filter-chip ${mode==='month'?'active':''}" data-action="taskMode" data-value="month">${C.monthLabel(ctx.month)}</button><button class="filter-chip ${mode==='overdue'?'active':''}" data-action="taskMode" data-value="overdue">Просроченные</button><button class="filter-chip ${mode==='all'?'active':''}" data-action="taskMode" data-value="all">Все задачи</button><input class="input search" id="taskSearch" placeholder="Поиск задачи" value="${attr(ctx.ui.taskSearch||'')}"><select class="select compact" id="taskOwner"><option value="all">Все ответственные</option>${owners.map(u=>`<option value="${attr(u.id)}" ${ownerFilter===u.id?'selected':''}>${esc(u.name)}</option>`).join('')}</select><select class="select compact" id="taskPriority"><option value="all">Любой приоритет</option>${Object.entries(C.PRIORITY).map(([k,v])=>`<option value="${k}" ${priority===k?'selected':''}>${esc(v)}</option>`).join('')}</select></div><div class="kanban">${C.STATUS_ORDER.map(status=>{const rows=filtered.filter(t=>t.status===status);return `<section class="kanban-col" data-status="${status}"><div class="kanban-head"><b>${esc(C.TASK_STATUS[status])}</b>${pill(String(rows.length))}</div><div class="kanban-body" data-drop-status="${status}">${rows.map(taskCard).join('')||empty('Пусто','Задач в этой колонке нет')}</div></section>`}).join('')}</div></div>`;
}
function calendarView(ctx){
 const [y,m]=ctx.month.split('-').map(Number),first=new Date(y,m-1,1),last=new Date(y,m,0),start=(first.getDay()+6)%7,total=Math.ceil((start+last.getDate())/7)*7,events=C.visible(C.getState().events),today=new Date().toISOString().slice(0,10),cells=[];
 for(let i=0;i<total;i++){const day=i-start+1,date=new Date(y,m-1,day),key=`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`,off=date.getMonth()!==m-1,items=events.filter(e=>e.date===key);cells.push(`<div class="calendar-day ${off?'off':''} ${key===today?'today':''}"><div class="day-number">${date.getDate()}</div>${items.map(e=>`<button class="event-chip ${attr(e.type)}" data-action="editEvent" data-id="${attr(e.id)}">${esc(e.time||'')} ${esc(e.title)}</button>`).join('')}</div>`)}
 return `<div class="page">${head(`Календарь · ${C.monthLabel(ctx.month)}`,'События и показатели автоматически относятся к выбранному месяцу',C.can('event.edit')?button('+ Мероприятие','addEvent','btn-primary'):'')}<div class="calendar"><div class="calendar-head">${['Пн','Вт','Ср','Чт','Пт','Сб','Вс'].map(x=>`<div>${x}</div>`).join('')}</div><div class="calendar-grid">${cells.join('')}</div></div><section class="grid grid-2"><article class="card">${cardTitle('События месяца','План и факт участников и выручки')}${eventRows(ctx.metrics.events)}</article><article class="card">${cardTitle('Чек-лист подготовки','Автоматический ритм T−30 → T+1')}<div class="simple-list">${['T−30 · Концепция и бюджет','T−21 · Запуск продаж','T−14 · Промежуточный контроль','T−7 · Участники и логистика','T−3 · Финальная организация','T−1 · Готовность','T+1 · Итоги и фактическая выручка'].map(x=>`<div class="list-row"><div class="grow"><b>${x}</b></div></div>`).join('')}</div></article></section></div>`;
}
function lineChart(values,labels){
 const w=620,h=210,p=30,max=Math.max(1,...values),pts=values.map((v,i)=>[p+(w-p*2)*(i/Math.max(1,values.length-1)),h-p-(h-p*2)*(v/max)]),poly=pts.map(p=>p.join(',')).join(' '),area=`${p},${h-p} ${poly} ${w-p},${h-p}`;
 return `<div class="chart"><svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><line class="axis" x1="${p}" y1="${h-p}" x2="${w-p}" y2="${h-p}"/><line class="axis" x1="${p}" y1="${p}" x2="${p}" y2="${h-p}"/><polygon class="chart-area" points="${area}"/><polyline class="chart-line" points="${poly}"/>${pts.map((q,i)=>`<circle class="chart-dot" cx="${q[0]}" cy="${q[1]}" r="4"/><text class="chart-label" x="${q[0]}" y="${h-8}" text-anchor="middle">${esc(labels[i]||'')}</text>`).join('')}</svg></div>`;
}
function barChart(values,labels){const w=560,h=210,p=28,max=Math.max(1,...values),bw=(w-p*2)/Math.max(1,values.length);return `<div class="chart"><svg viewBox="0 0 ${w} ${h}" preserveAspectRatio="none"><line class="axis" x1="${p}" y1="${h-p}" x2="${w-p}" y2="${h-p}"/>${values.map((v,i)=>{const bh=(h-p*2)*(v/max),x=p+i*bw+bw*.18,y=h-p-bh;return `<rect class="chart-bar ${i===values.length-1?'':'soft'}" x="${x}" y="${y}" width="${bw*.64}" height="${bh}"/><text class="chart-label" x="${x+bw*.32}" y="${h-8}" text-anchor="middle">${esc(labels[i]||'')}</text>`}).join('')}</svg></div>`}
function analyticsView(ctx){
 const m=ctx.metrics,archives=C.visible(C.getState().archives).sort((a,b)=>a.month.localeCompare(b)),historyMonths=[...new Set([...archives.map(a=>a.month),ctx.month])].sort().slice(-8),revenue=historyMonths.map(k=>k===ctx.month?m.revenue:Number(archives.find(a=>a.month===k)?.revenue||0)),plans=historyMonths.map(k=>Number(C.getState().months?.[k]?.target||0)),direction=m.directionStats;
 const cautious=Math.round(m.forecast*.88),base=m.forecast,strong=Math.round(m.forecast*1.18);
 return `<div class="page">${head('Аналитика и прогноз','Не текстовая заглушка: все графики строятся из общей базы месяца')}<article class="card hero"><div class="grid grid-2"><div><div class="eyebrow">БАЗОВЫЙ ПРОГНОЗ</div><div class="hero-value">${C.money(base)}</div><div class="hero-copy">При текущем дневном темпе. Выполнение плана — ${C.percent(m.forecastProgress)}.</div>${progress(m.forecastProgress)}</div><div class="forecast-grid"><div class="forecast-box"><small>Осторожный</small><b>${C.money(cautious)}</b></div><div class="forecast-box active"><small>Базовый</small><b>${C.money(base)}</b></div><div class="forecast-box"><small>Сильный</small><b>${C.money(strong)}</b></div><div class="forecast-box"><small>План</small><b>${C.money(m.plan.target)}</b></div></div></div></article>
 <section class="grid grid-2"><article class="chart-panel"><h3>Выручка по месяцам</h3><p>Факт закрытых месяцев и текущий месяц</p>${lineChart(revenue,historyMonths.map(k=>C.SHORT_MONTHS[Number(k.slice(5,7))-1]))}</article><article class="chart-panel"><h3>План по месяцам</h3><p>Целевые значения учебного года</p>${barChart(plans,historyMonths.map(k=>C.SHORT_MONTHS[Number(k.slice(5,7))-1]))}</article></section>
 <section class="grid grid-2"><article class="chart-panel"><h3>Загрузка направлений</h3><p>Данные всех групп наставников</p>${barChart(direction.map(x=>x.occupancy),direction.map(x=>dirName(x.direction)))}</article><article class="chart-panel"><h3>Выполнение задач</h3><p>Выбранный месяц</p>${barChart(C.STATUS_ORDER.map(s=>m.tasks.filter(t=>t.status===s).length),C.STATUS_ORDER.map(s=>C.TASK_STATUS[s]))}</article></section>
 <section class="grid grid-4">${metric('Вероятность минимума',C.percent(probability(base,m.plan.min)),C.money(m.plan.min),'●',probability(base,m.plan.min))}${metric('Вероятность плана',C.percent(probability(base,m.plan.target)),C.money(m.plan.target),'●',probability(base,m.plan.target))}${metric('Вероятность сильного',C.percent(probability(base,m.plan.stretch)),C.money(m.plan.stretch),'●',probability(base,m.plan.stretch))}${metric('Дневной темп',C.money(m.pace),'средняя выручка в день','↗')}</section>
 <article class="card">${cardTitle('Что изменить, чтобы улучшить прогноз','Рекомендации строятся из текущих показателей')}${analyticsRecommendations(m)}</article></div>`;
}
function probability(forecast,target){if(!target)return 0;const ratio=forecast/target;return C.clamp((ratio-.65)*160,5,98)}
function analyticsRecommendations(m){const rec=[];if(m.free>0)rec.push(`В расписании свободно ${m.free} мест. Приоритет — группы ниже 60% загрузки.`);if(m.overdue.length)rec.push(`Закрыть или перепланировать ${m.overdue.length} просроченных задач.`);if(m.conversion<45)rec.push(`Конверсия ${C.percent(m.conversion)}. Проверить сообщения после пробной и скорость контакта.`);if(m.renewal<70)rec.push(`Продления ${C.percent(m.renewal)}. Сформировать список абонементов, заканчивающихся за 7 дней.`);if(m.forecast<m.plan.target)rec.push(`До плана по прогнозу не хватает ${C.money(m.plan.target-m.forecast)}. Разложить разрыв на продления, новые продажи и события.`);if(!rec.length)rec.push('Ключевые показатели находятся в целевой зоне. Сохраняйте темп и контролируйте качество.');return `<div class="simple-list">${rec.map(x=>`<div class="alert-row"><i></i><div><b>${esc(x)}</b></div></div>`).join('')}</div>`}
function archiveView(ctx){const archives=C.visible(C.getState().archives).sort((a,b)=>b.month.localeCompare(a.month)),deleted=(C.getState().tasks||[]).filter(t=>t.deletedAt);return `<div class="page">${head('Архив','Закрытые месяцы и история без потери удалённых задач',C.can('archive.create')?button(`Закрыть ${C.monthLabel(ctx.month)}`,'archiveMonth','btn-primary'):'')}<section class="grid grid-3">${archives.length?archives.map(a=>`<article class="card"><div class="eyebrow">${esc(C.monthLabel(a.month))}</div><div class="metric-value">${C.money(a.revenue)}</div><div class="metric-sub">план ${C.money(a.plan?.target||0)}</div>${progress(a.plan?.target?a.revenue/a.plan.target*100:0)}<div class="status-row">${pill(`Загрузка ${C.percent(a.occupancy)}`)}${pill(`Задачи ${a.doneTasks}/${a.tasks}`)}${pill(`События ${a.events}`)}</div></article>`).join(''):empty('Архив пока пуст','Закройте первый месяц после финальной сверки')}</section>${C.can('task.restore')?`<article class="card">${cardTitle('Удалённые задачи','Удалять задачи могут только Роман и Софа; записи сохраняются как история')}${deleted.length?`<div class="simple-list">${deleted.slice(0,50).map(t=>`<div class="list-row"><div class="grow"><b>${esc(t.title)}</b><small>Удалил: ${esc(user(t.deletedBy).name)} · ${fmtDate(t.deletedAt)}</small></div><button class="btn btn-small btn-ghost" data-action="restoreTask" data-id="${attr(t.id)}">Восстановить</button></div>`).join('')}</div>`:empty('Удалённых задач нет','Здесь появятся задачи после удаления')}</article>`:''}</div>`}
function salesTable(month,adminId='all'){let rows=C.visible(C.getState().sales).filter(s=>String(s.date||s.createdAt||'').slice(0,7)===month&&(adminId==='all'||s.adminId===adminId));return rows.length?`<div class="table-wrap"><table class="data-table"><thead><tr><th>Дата</th><th>Администратор</th><th>Клиент</th><th>Тип</th><th>Сумма</th><th></th></tr></thead><tbody>${rows.sort((a,b)=>String(b.date).localeCompare(String(a.date))).map(s=>`<tr><td>${fmtDate(s.date||s.createdAt)}</td><td>${esc(user(s.adminId).name)}</td><td><span class="strong">${esc(s.clientName||'Клиент')}</span></td><td>${esc(saleType(s.type))}</td><td><span class="strong">${C.money(s.amount)}</span></td><td>${C.can('sale.edit')?`<button class="btn btn-small btn-ghost" data-action="editSale" data-id="${attr(s.id)}">Открыть</button>`:''}</td></tr>`).join('')}</tbody></table></div>`:empty('Продаж нет','Добавьте оплаты, продления, лагерь или мероприятие — аналитика обновится сразу',C.can('sale.edit')?button('+ Продажа','addSale','btn-primary'):'')}
function settingsView(ctx){
 const access=C.getAccess(),roles=[['owner','roman','Роман · владелец'],['manager','sofa','Софа · управляющая'],['head','stas','Стас · руководитель'],['mentor','ivan','Наставник'],['admin','anya','Администратор'],['team','team','Командный экран']];
 return `<div class="page">${head('Настройки и доступы','Рабочее пространство, роли, синхронизация и резервные копии')}<section class="settings-grid"><article class="card">${cardTitle('Общая база','Один workspace для всех ролей')}<div class="access-link"><small>Рабочее пространство</small><code>${esc(access.workspace)}</code></div><div class="status-row">${pill('AES-GCM шифрование','green')}${pill(`Схема ${C.SCHEMA}`)}${pill(`Версия ${C.VERSION}`)}</div><div class="head-actions" style="margin-top:14px">${button('Синхронизировать','syncNow','btn-primary')}${button('Экспорт JSON','exportData')}${button('Импорт JSON','importData')}</div></article><article class="card">${cardTitle('Автоматическое обновление','Как данные поднимаются вверх')}<div class="source-flow"><span class="source-node">Наставники</span><span class="source-arrow">→</span><span class="source-node">Руководитель</span><span class="source-arrow">→</span><span class="source-node">Софа</span><span class="source-arrow">→</span><span class="source-node">Роман</span></div><p style="color:var(--muted)">Все кабинеты читают одни и те же первичные данные. Итоги не копируются — они рассчитываются при каждом обновлении.</p></article></section>
 <article class="card">${cardTitle('Персональные ссылки','Полная ссылка содержит ключ. Передавайте её только нужному сотруднику')}<div class="grid grid-3">${roles.map(([role,id,label])=>`<div class="access-link"><b>${esc(label)}</b><code>${esc(C.shareLink(role,id))}</code><button class="btn btn-small ${role==='manager'?'btn-primary':'btn-ghost'}" data-action="copyAccess" data-role="${role}" data-user="${id}">Скопировать ссылку</button></div>`).join('')}</div></article>
 <section class="settings-grid"><article class="card">${cardTitle('Профиль Софы','Новая роль управляющей в общей системе')}<p style="color:var(--muted)">Софа видит операционные показатели, наставников, продажи и цели, ставит задачи администраторам и вместе с Романом может удалять задачи.</p><div class="head-actions"><button class="btn btn-primary" data-action="copySofaLink">Скопировать ссылку Софы</button><a class="btn btn-ghost" href="https://extreme-kids-troparevo-control.vercel.app/" target="_blank" rel="noopener">Текущий сайт Софы</a></div></article><article class="card">${cardTitle('Перенос из Growth OS 6.0','Старая база не перезаписывается')}<p style="color:var(--muted)">Статус миграции: ${esc(C.getState().meta?.legacyStatus||C.getLegacyStatus())}. Резервная копия старого состояния сохраняется локально перед импортом.</p>${button('Повторить импорт старой базы','retryLegacyImport')}</article></section>
 <article class="card">${cardTitle('Журнал изменений','Последние действия в общей базе')}<div class="audit-list">${(C.getState().audit||[]).slice(0,100).map(a=>`<div class="audit-row"><time>${fmtDate(a.createdAt)}</time><small>${esc(user(a.actorId).name)}</small><div><b>${esc(a.action)}</b>${a.details&&Object.keys(a.details).length?`<br><small>${esc(JSON.stringify(a.details))}</small>`:''}</div></div>`).join('')||empty('Журнал пуст','Изменения появятся после первой операции')}</div></article></div>`;
}
function render(view,ctx){
 const enriched={...ctx,metrics:C.derive(ctx.month)};switch(view){case'dashboard':return ownerDashboard(enriched);case'manager':return managerDashboard(enriched);case'year':return yearView(enriched);case'groups':return groupsView(enriched);case'goals':return goalsView(enriched);case'tasks':return tasksView(enriched);case'calendar':return calendarView(enriched);case'analytics':return analyticsView(enriched);case'archive':return archiveView(enriched);case'stas':return headDashboard(enriched);case'mentor':return mentorDashboard(enriched);case'admin':return adminDashboard(enriched);case'team':return teamDashboard(enriched);case'settings':return settingsView(enriched);default:return ownerDashboard(enriched)}}
window.EK61_VIEWS={render,pageMeta,esc,fmtDate,user,dirName,typeName,saleType,taskCard};
})();
