'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');const root=path.resolve(__dirname,'..');
const source=path.join(root,'source/index.html');let html=fs.readFileSync(source,'utf8');
const hook="document.addEventListener('click',handleClick);";
if(html.split(hook).length!==2)throw Error('Unexpected original bootstrap');
html=html.replace(hook,['sofa-cabinet-v4.patch.js','sofa-cabinet-v4.1.patch.js','audit65-fixes.patch.js'].map(n=>fs.readFileSync(path.join(root,'source',n),'utf8')).join('\n')+'\n'+hook);
html=html.replace("const today=()=>new Date().toISOString().slice(0,10);", "const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Moscow',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());");
const styles=[...html.matchAll(/<style[^>]*>([\s\S]*?)<\/style>/gi)].map(x=>x[1]).join('\n');
const scripts=[...html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/gi)].map(x=>x[1]);if(scripts.length!==1)throw Error('Unexpected script count');let js=scripts[0];
const marker="document.addEventListener('click',handleClick);";if(js.split(marker).length!==2)throw Error('Ambiguous bootstrap marker');
js=js.replace('let credentials=parseCredentials();',"let credentials={workspace:'secure',role:'team',token:''};");
js=js.replace(/const AUGUST_ADMIN_SNAPSHOT=\{[\s\S]*?\n\};/,"const AUGUST_ADMIN_SNAPSHOT={monthKey:'2026-08',clubRevenue:0,admins:{}};");
if(/955889|54602\.03|99602\.03/.test(js))throw Error('Legacy payroll fixture not removed');
js=js.replaceAll('fact:2162988','fact:0');
js=js.replaceAll('https://mantledb.sh/v2/','/api/disabled-legacy/');
js=js.replace("if(!/^([01]\\d|2[0-3]):[0-5]\\d$/.test(v.time||''))", "if(!/^([01]\\d|2[0-3]):[0-5]\\d(?:[–-]([01]\\d|2[0-3]):[0-5]\\d)?$/.test(v.time||''))");
js=js.replace(marker,fs.readFileSync(path.join(root,'lib/client-bridge.js'),'utf8')+'\n'+marker);
// Do not export legacy credentials or the reset entry point through diagnostics.
js=js.replace(/window\.EKGrowthOS=\{version:VERSION,build:BUILD,getState:[^\n]+;/,"window.EKGrowthOS={version:VERSION,build:BUILD,getState:()=>state,setView,sync:()=>syncNow({quiet:true})};");
fs.mkdirSync(path.join(root,'build'),{recursive:true});fs.writeFileSync(path.join(root,'build/app.js'),js);
fs.writeFileSync(path.join(root,'public/app.css'),styles+'\n.top-title>div{min-width:0;overflow:hidden}.top-title .crumb{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.mobile-menu-btn{flex-shrink:0} @media(max-width:560px){.top-actions{flex-wrap:wrap;max-width:50%}.topbar{height:auto;min-height:72px}.top-actions>[data-action="s65Logout"]{font-size:11px;padding:6px}.top-title{min-width:0}}');
html=html.replace(/<style[^>]*>[\s\S]*?<\/style>/gi,'').replace(/<script[^>]*>[\s\S]*?<\/script>/gi,'').replace('</head>','<link rel="stylesheet" href="/app.css"><script src="/model.js" defer></script><script src="/api/app" defer></script></head>');
fs.writeFileSync(path.join(root,'public/app.html'),html);
fs.writeFileSync(path.join(root,'build/manifest.json'),JSON.stringify({version:'6.5-security.1',builtAt:new Date().toISOString(),sha256:crypto.createHash('sha256').update(js).digest('hex'),sourceSha256:crypto.createHash('sha256').update(fs.readFileSync(source)).digest('hex'),transport:'authenticated same-origin API',legacyTransport:false},null,2));
console.log('Built Growth OS 6.5 secure bundle');
