// ATTENDANCE_INTELLIGENCE_V1_START
const ATTENDANCE_EXTENSION_BUILD='2026.09.01-weekly-attendance-intelligence';
const ATTENDANCE_STATUS={
  present:'Пришёл',sick:'Заболел',warned:'Предупредили',vacation:'Отпуск',freeze:'Заморозка',noShow:'Неявка',unknown:'Не отмечен'
};
const ATTENDANCE_STATUS_SHORT={present:'Пришёл',sick:'Болезнь',warned:'Предупредили',vacation:'Отпуск',freeze:'Заморозка',noShow:'Неявка',unknown:'—'};
const ATTENDANCE_DAY_INDEX={Понедельник:0,Вторник:1,Среда:2,Четверг:3,Пятница:4,Суббота:5,Воскресенье:6};
const ATTENDANCE_DEFAULTS={
  fillGood:75,attendanceGood:80,densityGood:70,lowDensity:50,consecutiveMisses:2,autoTasks:true,forecastWeeks:8
};

ICONS.attendance='<svg viewBox="0 0 24 24"><path d="M4 19V9m5 10V5m5 14v-7m5 7V3"/><path d="M3 21h18"/><circle cx="4" cy="7" r="2"/><circle cx="9" cy="3" r="2"/><circle cx="14" cy="10" r="2"/><circle cx="19" cy="1" r="2"/></svg>';
const attendanceWorkSection=NAV.find(section=>section.section==='Работа');
if(attendanceWorkSection&&!attendanceWorkSection.items.some(x=>x.id==='attendance')){
  attendanceWorkSection.items.splice(2,0,{id:'attendance',label:'Посещаемость',icon:'attendance',roles:['owner','manager','stas','mentor','admin']});
}

function attendanceIsoDate(value=new Date()){
  const d=value instanceof Date?new Date(value):new Date(String(value).length===10?String(value)+'T12:00:00':value);
  if(Number.isNaN(+d))return today();
  const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');
  return`${y}-${m}-${day}`;
}
function attendanceAddDays(value,days){const d=new Date(attendanceIsoDate(value)+'T12:00:00');d.setDate(d.getDate()+Number(days||0));return attendanceIsoDate(d)}
function attendanceWeekStart(value=today()){
  const d=new Date(attendanceIsoDate(value)+'T12:00:00'),delta=(d.getDay()+6)%7;d.setDate(d.getDate()-delta);return attendanceIsoDate(d);
}
function attendanceWeekEnd(weekKey){return attendanceAddDays(attendanceWeekStart(weekKey),6)}
function attendanceWeekLabel(weekKey){
  const start=new Date(attendanceWeekStart(weekKey)+'T12:00:00'),end=new Date(attendanceWeekEnd(weekKey)+'T12:00:00');
  const a=new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'short'}).format(start),b=new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'short',year:'numeric'}).format(end);
  return`${a} — ${b}`;
}
function attendanceSelectedWeek(){return attendanceWeekStart(state?.ui?.attendanceWeek||today())}
function attendanceWeekDateForGroup(group,weekKey=attendanceSelectedWeek()){return attendanceAddDays(weekKey,ATTENDANCE_DAY_INDEX[group?.day]??0)}
function attendanceInWeek(date,weekKey){return String(date||'')>=attendanceWeekStart(weekKey)&&String(date||'')<=attendanceWeekEnd(weekKey)}
function attendanceLive(x){return x&&!x.deletedAt&&x.active!==false}
function attendanceSessionActual(s){return attendanceLive(s)&&s.mode!=='planned'&&s.status!=='cancelled'}
function attendanceSessions(){return(state.attendanceSessions||[]).filter(attendanceLive)}
function attendanceChildren(){return(state.attendanceChildren||[]).filter(attendanceLive)}
function attendanceMemberships(){return(state.attendanceMemberships||[]).filter(attendanceLive)}
function attendanceArchives(){return(state.attendanceWeekArchives||[]).filter(attendanceLive)}
function attendanceSettings(){return{...ATTENDANCE_DEFAULTS,...(state.attendanceSettings||{})}}
function attendanceMembers(groupId){
  const childMap=new Map(attendanceChildren().map(c=>[c.id,c]));
  return attendanceMemberships().filter(m=>m.groupId===groupId&&m.status!=='inactive').map(m=>({membership:m,child:childMap.get(m.childId)})).filter(x=>x.child);
}
function attendanceEnrolled(group){const count=attendanceMembers(group.id).length;return group.rosterManaged?count:Math.max(Number(group.students)||0,count)}
function attendanceCapacity(group,sessions=[]){return Number(sessions[0]?.capacitySnapshot)||Number(group?.capacity)||0}
function attendanceSessionCounts(s){
  const records=Array.isArray(s.records)?s.records:[],count=status=>records.filter(r=>r.status===status).length;
  const fromRecords=records.length>0;
  const present=fromRecords?count('present'):Number(s.presentCount)||0;
  const sick=fromRecords?count('sick'):Number(s.sickCount)||0;
  const warned=fromRecords?count('warned'):Number(s.warnedCount)||0;
  const vacation=fromRecords?count('vacation'):Number(s.vacationCount)||0;
  const freeze=fromRecords?count('freeze'):Number(s.freezeCount)||0;
  const noShow=fromRecords?count('noShow'):Number(s.noShowCount)||0;
  const unknown=fromRecords?count('unknown'):Math.max(0,(Number(s.expectedCount)||0)-present-sick-warned-noShow);
  const makeup=Number(s.makeupCount)||0,trial=Number(s.trialCount)||0,guest=Number(s.guestCount)||0;
  const expected=Math.max(Number(s.expectedCount)||0,present+sick+warned+noShow+unknown);
  const actual=present+makeup+trial+guest;
  return{expected,present,sick,warned,vacation,freeze,noShow,unknown,makeup,trial,guest,actual,objective:sick+warned+vacation+freeze};
}
function attendanceGroupWeekStats(group,weekKey=attendanceSelectedWeek(),includePlanned=false){
  const sessions=attendanceSessions().filter(s=>s.groupId===group.id&&attendanceInWeek(s.date,weekKey)&&(includePlanned||attendanceSessionActual(s)));
  const actualSessions=sessions.filter(attendanceSessionActual),source=includePlanned?sessions:actualSessions;
  const totals=source.reduce((a,s)=>{const c=attendanceSessionCounts(s);Object.keys(c).forEach(k=>a[k]=(a[k]||0)+(Number(c[k])||0));return a},{expected:0,present:0,sick:0,warned:0,vacation:0,freeze:0,noShow:0,unknown:0,makeup:0,trial:0,guest:0,actual:0,objective:0});
  const enrolledSlots=source.reduce((a,s)=>a+(Number(s.enrolledSnapshot)||attendanceEnrolled(group)),0);
  const capacitySlots=source.reduce((a,s)=>a+(Number(s.capacitySnapshot)||Number(group.capacity)||0),0);
  const enrolled=attendanceEnrolled(group),capacity=Number(group.capacity)||0;
  const fill=capacity?enrolled/capacity*100:0;
  const attendance=totals.expected?totals.present/totals.expected*100:0;
  const density=capacitySlots?totals.actual/capacitySlots*100:0;
  return{group,weekKey,sessions,actualSessions,sessionCount:actualSessions.length,enrolled,capacity,enrolledSlots,capacitySlots,...totals,fill,attendance,density,hasData:actualSessions.length>0};
}
function attendanceAggregate(groups,weekKey=attendanceSelectedWeek()){
  const stats=groups.map(g=>attendanceGroupWeekStats(g,weekKey)),withData=stats.filter(x=>x.hasData);
  const enrolledSlots=sum(withData,x=>x.enrolledSlots),capacitySlots=sum(withData,x=>x.capacitySlots),expected=sum(withData,x=>x.expected),present=sum(withData,x=>x.present),actual=sum(withData,x=>x.actual);
  const currentCapacity=sum(groups,g=>Number(g.capacity)||0),currentEnrolled=sum(groups,g=>attendanceEnrolled(g));
  return{weekKey,stats,withData,groups:groups.length,sessions:sum(withData,x=>x.sessionCount),currentCapacity,currentEnrolled,fill:currentCapacity?currentEnrolled/currentCapacity*100:0,attendance:expected?present/expected*100:0,density:capacitySlots?actual/capacitySlots*100:0,expected,present,actual,objective:sum(withData,x=>x.objective),sick:sum(withData,x=>x.sick),warned:sum(withData,x=>x.warned),vacation:sum(withData,x=>x.vacation),freeze:sum(withData,x=>x.freeze),noShow:sum(withData,x=>x.noShow),makeup:sum(withData,x=>x.makeup),trial:sum(withData,x=>x.trial),guest:sum(withData,x=>x.guest),completeness:groups.length?withData.length/groups.length*100:0};
}
function attendanceScopeGroups(){
  const all=activeGroups();
  if(currentRole==='mentor')return all.filter(g=>g.mentorId===mentorViewerId());
  if(currentRole==='stas')return all.filter(g=>['stas','ivan','tasya','karina'].includes(g.mentorId)||/ролик|фигур/i.test(g.discipline||g.name));
  return all;
}
function attendanceMentorIds(groups=attendanceScopeGroups()){return[...new Set(groups.map(g=>g.mentorId))]}
function attendanceMentorWeekStats(mentorId,weekKey=attendanceSelectedWeek()){
  const groups=attendanceScopeGroups().filter(g=>g.mentorId===mentorId),agg=attendanceAggregate(groups,weekKey),expectedLogs=groups.length,logged=agg.withData.length;
  const tasks=activeTasks().filter(t=>t.linkType==='attendance'&&t.ownerId===mentorId&&attendanceInWeek(t.attendanceWeek||t.deadline,weekKey));
  const done=tasks.filter(t=>statusDone(t.status)).length;
  const followup=tasks.length?done/tasks.length*100:100,logging=expectedLogs?logged/expectedLogs*100:0,workIndex=logging*.65+followup*.35;
  return{mentorId,p:person(mentorId),groups,agg,logging,followup,workIndex,tasks,done};
}
function attendanceWeekSeries(groups,endWeek=attendanceSelectedWeek(),weeks=8){
  const result=[];for(let i=weeks-1;i>=0;i--){const key=attendanceAddDays(endWeek,-7*i),a=attendanceAggregate(groups,key);result.push({key,label:attendanceWeekLabel(key),...a})}return result;
}
function attendanceGroupTrend(group,endWeek=attendanceSelectedWeek(),weeks=4){return attendanceWeekSeries([group],endWeek,weeks).map(x=>x.sessions?Math.round(x.actual/Math.max(1,x.sessions)):null)}
function attendanceTrendText(values){return values.map(v=>v==null?'—':String(v)).join(' → ')}
function attendanceForecastGroup(group,nextWeek=attendanceAddDays(attendanceSelectedWeek(),7)){
  const settings=attendanceSettings(),series=attendanceWeekSeries([group],attendanceAddDays(nextWeek,-7),settings.forecastWeeks).filter(x=>x.sessions>0),enrolled=attendanceEnrolled(group),capacity=Number(group.capacity)||0;
  const rates=series.map(x=>x.expected?x.present/x.expected:0).filter(Number.isFinite),actuals=series.map(x=>x.sessions?x.actual/x.sessions:0);
  let base,spread,method,confidence;
  if(rates.length>=2){const weights=rates.map((_,i)=>i+1),ws=sum(weights),rate=rates.reduce((a,v,i)=>a+v*weights[i],0)/ws;base=enrolled*rate;const mean=avg(actuals),sd=Math.sqrt(avg(actuals.map(v=>(v-mean)**2)));spread=Math.max(.75,sd);method=`${rates.length} недель`;confidence=rates.length>=6?'высокая':rates.length>=4?'средняя':'низкая'}
  else{base=enrolled*.78;spread=Math.max(1,enrolled*.18);method='стартовая оценка';confidence='низкая'}
  const planned=attendanceSessions().filter(s=>s.groupId===group.id&&attendanceInWeek(s.date,nextWeek)&&s.mode==='planned'),knownAbs=sum(planned,s=>{const c=attendanceSessionCounts(s);return c.sick+c.vacation+c.freeze+c.warned});
  base=Math.max(0,base-knownAbs);const low=Math.max(0,Math.floor(base-spread)),high=Math.min(Math.max(capacity,enrolled),Math.ceil(base+spread));
  return{group,nextWeek,low,high,base:Math.round(base*10)/10,confidence,method,knownAbs};
}
function attendanceForecast(groups=attendanceScopeGroups(),nextWeek=attendanceAddDays(attendanceSelectedWeek(),7)){
  const rows=groups.map(g=>attendanceForecastGroup(g,nextWeek)),low=sum(rows,x=>x.low),high=sum(rows,x=>x.high),base=sum(rows,x=>x.base);return{rows,low,high,base,nextWeek};
}
function attendanceChildMissSignals(groups,weekKey=attendanceSelectedWeek()){
  const groupIds=new Set(groups.map(g=>g.id)),members=attendanceMemberships().filter(m=>groupIds.has(m.groupId)),childrenMap=new Map(attendanceChildren().map(c=>[c.id,c])),signals=[];
  for(const m of members){const sessions=attendanceSessions().filter(s=>s.groupId===m.groupId&&attendanceSessionActual(s)&&s.date<=attendanceWeekEnd(weekKey)).sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,4);const records=sessions.map(s=>({s,r:(s.records||[]).find(r=>r.childId===m.childId)})).filter(x=>x.r);let streak=0,last=[];for(const x of records){if(['sick','warned','vacation','freeze','noShow'].includes(x.r.status)){streak++;last.push(x)}else break}if(streak>=attendanceSettings().consecutiveMisses){const child=childrenMap.get(m.childId),g=groups.find(x=>x.id===m.groupId),unexcused=last.some(x=>x.r.status==='noShow');signals.push({kind:unexcused?'red':'gold',title:`${child?.name||'Ребёнок'} пропустил ${streak} занятия подряд`,text:`${g?.name||'Группа'} · ${unexcused?'есть неявка без предупреждения':'причины отмечены'} · нужен контакт перед следующим занятием`,groupId:m.groupId,childId:m.childId,task:{key:`child-${m.childId}-${weekKey}`,ownerId:(state.people.find(p=>p.role==='admin'&&p.active!==false)?.id)||g?.mentorId||'roman',title:`Связаться после повторных пропусков: ${child?.name||'ребёнок'}`,description:`Группа: ${g?.name||'—'}. Пропущено подряд: ${streak}. Уточнить возвращение и зафиксировать результат вместе с наставником.`}})}}
  return signals;
}
function attendanceSignals(groups=attendanceScopeGroups(),weekKey=attendanceSelectedWeek()){
  const a=attendanceAggregate(groups,weekKey),settings=attendanceSettings(),signals=[];
  if(!a.sessions)signals.push({kind:'gold',title:'Неделя ещё не заполнена',text:'Отметьте фактическое посещение после каждой тренировки — показатели и прогноз появятся автоматически.'});
  else if(a.completeness<70)signals.push({kind:'gold',title:`Учёт заполнен на ${Math.round(a.completeness)}%`,text:`Есть данные по ${a.withData.length} из ${a.groups} групп. Незаполненные тренировки не считаются нулевой посещаемостью.`});
  for(const s of a.stats){if(!s.hasData)continue;
    if(s.fill>=80&&s.density<55)signals.push({kind:'gold',title:`${s.group.name}: запись высокая, плотность низкая`,text:`Закреплено ${s.enrolled}/${s.capacity}, фактически ${Math.round(s.density)}%. Проверьте болезни, заморозки и регулярность.`,groupId:s.group.id});
    if(s.fill<50&&s.attendance>=80)signals.push({kind:'gold',title:`${s.group.name}: ходят стабильно, но группа недопродана`,text:`Посещаемость ${Math.round(s.attendance)}%, заполненность ${Math.round(s.fill)}%. Это задача продаж, а не качества наставника.`,groupId:s.group.id});
    const prev=attendanceGroupWeekStats(s.group,attendanceAddDays(weekKey,-7));if(s.density<settings.lowDensity&&prev.hasData&&prev.density<settings.lowDensity)signals.push({kind:'red',title:`${s.group.name}: плотность ниже ${settings.lowDensity}% две недели`,text:`Сейчас ${Math.round(s.density)}%, неделей ранее ${Math.round(prev.density)}%. Нужен разбор времени, состава и удержания.`,groupId:s.group.id,task:{key:`density-${s.group.id}-${weekKey}`,ownerId:s.group.mentorId,title:`Разобрать низкую посещаемость: ${s.group.name}`,description:`Фактическая плотность ниже ${settings.lowDensity}% две недели подряд. Совместно с администратором проверить состав, причины пропусков и план возврата.`}});
    const four=attendanceWeekSeries([s.group],weekKey,4);if(four.filter(x=>x.sessions&&x.density>=settings.densityGood).length>=3&&s.fill>=85)signals.push({kind:'gold',title:`${s.group.name}: кандидат на лист ожидания`,text:'Высокая заполненность и фактическая плотность минимум три недели из четырёх. Можно оценить дополнительный слот.',groupId:s.group.id});
  }
  if(a.noShow)signals.push({kind:'red',title:`Неявки без предупреждения: ${a.noShow}`,text:'Администратору нужно связаться с семьями и зафиксировать результат контакта.'});
  return[...attendanceChildMissSignals(groups,weekKey),...signals];
}
function attendanceTaskDeadline(weekKey){const d=attendanceAddDays(attendanceWeekEnd(weekKey),1);return d<today()?today():d}
function attendanceReconcileTasks(weekKey=attendanceSelectedWeek()){
  if(!attendanceSettings().autoTasks)return 0;let created=0;
  for(const signal of attendanceSignals(attendanceScopeGroups(),weekKey).filter(x=>x.task)){
    const key=`attendance:${signal.task.key}`;if(activeTasks().some(t=>t.attendanceAlertKey===key))continue;
    state.tasks.push({id:id('task'),title:signal.task.title,description:signal.task.description,ownerId:signal.task.ownerId,monthKey:monthKeyFromDate(weekKey),deadline:attendanceTaskDeadline(weekKey),priority:signal.kind==='red'?'high':'medium',status:'todo',required:false,linkType:'attendance',linkId:signal.groupId||'',attendanceAlertKey:key,attendanceWeek:weekKey,createdBy:'attendance',createdAt:nowIso(),updatedAt:nowIso()});created++;
  }
  return created;
}
function attendanceEnsure(s){
  if(!s||typeof s!=='object')return s;s.attendanceSettings={...ATTENDANCE_DEFAULTS,...(s.attendanceSettings||{})};
  s.attendanceChildren=Array.isArray(s.attendanceChildren)?s.attendanceChildren:[];s.attendanceMemberships=Array.isArray(s.attendanceMemberships)?s.attendanceMemberships:[];s.attendanceSessions=Array.isArray(s.attendanceSessions)?s.attendanceSessions:[];s.attendanceWeekArchives=Array.isArray(s.attendanceWeekArchives)?s.attendanceWeekArchives:[];
  s.ui={...(s.ui||{}),attendanceWeek:attendanceWeekStart(s.ui?.attendanceWeek||today()),attendanceTab:s.ui?.attendanceTab||'overview',attendanceMentor:s.ui?.attendanceMentor||'all',attendanceGroup:s.ui?.attendanceGroup||'all'};s.meta=s.meta||{};s.meta.attendanceBuild=ATTENDANCE_EXTENSION_BUILD;return s;
}
const __seedStateAttendanceBase=seedState;seedState=function(){return attendanceEnsure(__seedStateAttendanceBase())};
const __ensureStateAttendanceBase=ensureState;ensureState=function(raw){return attendanceEnsure(__ensureStateAttendanceBase(raw))};
const __mergeStatesAttendanceBase=mergeStates;mergeStates=function(local,remote){const out=attendanceEnsure(__mergeStatesAttendanceBase(local,remote));if(!remote)return out;out.attendanceChildren=mergeLists(local?.attendanceChildren||[],remote?.attendanceChildren||[]);out.attendanceMemberships=mergeLists(local?.attendanceMemberships||[],remote?.attendanceMemberships||[]);out.attendanceSessions=mergeLists(local?.attendanceSessions||[],remote?.attendanceSessions||[]);out.attendanceWeekArchives=mergeLists(local?.attendanceWeekArchives||[],remote?.attendanceWeekArchives||[]);out.attendanceSettings={...ATTENDANCE_DEFAULTS,...(local?.attendanceSettings||{}),...(remote?.attendanceSettings||{})};return attendanceEnsure(out)};

function attendancePct(value){return Number.isFinite(value)?`${Math.round(value)}%`:'—'}
function attendanceValue(value){return Number.isFinite(Number(value))?String(Math.round(Number(value))):'—'}
function attendanceMetric(label,value,sub,progressValue=null,kind=''){return`<article class="card attendance-metric ${kind}"><span>${esc(label)}</span><b>${value}</b><small>${esc(sub)}</small>${progressValue===null?'':`<div class="progress"><i style="width:${clamp(progressValue,0,100)}%"></i></div>`}</article>`}
function attendanceTabs(active){const tabs=[['overview','Эта неделя'],['groups','Группы'],['mentors','Наставники'],['log','Журнал'],['forecast','Прогноз'],['archive','Архив недель']];return`<div class="attendance-tabs">${tabs.map(([idv,label])=>`<button class="${active===idv?'active':''}" data-action="attendanceTab" data-tab="${idv}">${label}</button>`).join('')}</div>`}
function attendanceWeekToolbar(){const week=attendanceSelectedWeek();return`<div class="attendance-weekbar"><div class="attendance-week-nav"><button class="icon-btn" data-action="attendancePrevWeek" title="Предыдущая неделя">‹</button><div><span>Рабочая неделя</span><b>${esc(attendanceWeekLabel(week))}</b></div><button class="icon-btn" data-action="attendanceNextWeek" title="Следующая неделя">›</button><button class="btn btn-small btn-ghost" data-action="attendanceCurrentWeek">Текущая</button></div><div class="attendance-week-actions"><button class="btn btn-ghost" data-action="attendanceAddChild">+ Ребёнок</button><button class="btn btn-primary" data-action="attendanceAddSession">+ Отметить тренировку</button></div></div>`}
function attendanceReasonGrid(a){const rows=[['Болезнь',a.sick,'sick'],['Предупредили',a.warned,'warned'],['Отпуск / заморозка',a.vacation+a.freeze,'vacation'],['Неявка',a.noShow,'noShow'],['Отработка',a.makeup,'makeup'],['Пробные / гости',a.trial+a.guest,'guest']];return`<div class="attendance-reasons">${rows.map(([label,v,k])=>`<div class="attendance-reason ${k}"><i></i><span>${label}</span><b>${v}</b></div>`).join('')}</div>`}
function attendanceTrendChart(series,metric='density'){
  const data=series.filter(x=>x.sessions>0);if(data.length<2)return`<div class="empty"><b>Недостаточно истории</b>После двух заполненных недель появится диаграмма динамики.</div>`;
  const W=760,H=240,P=34,max=100,pts=data.map((x,i)=>[P+(W-2*P)*(i/Math.max(1,data.length-1)),H-P-(H-2*P)*(clamp(x[metric],0,100)/max)]),path=pts.map((p,i)=>(i?'L':'M')+p[0].toFixed(1)+' '+p[1].toFixed(1)).join(' '),area=path+` L ${pts.at(-1)[0]} ${H-P} L ${pts[0][0]} ${H-P} Z`;
  return`<svg class="attendance-chart" viewBox="0 0 ${W} ${H}" preserveAspectRatio="none"><defs><linearGradient id="attGoldArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#ffdc55" stop-opacity=".34"/><stop offset="1" stop-color="#f0c72f" stop-opacity="0"/></linearGradient></defs>${[25,50,75,100].map(v=>{const y=H-P-(H-2*P)*v/100;return`<line x1="${P}" y1="${y}" x2="${W-P}" y2="${y}" class="attendance-gridline"/><text x="4" y="${y+4}" class="attendance-axis-label">${v}%</text>`}).join('')}<path d="${area}" fill="url(#attGoldArea)"/><path d="${path}" class="attendance-chart-line"/>${pts.map((p,i)=>`<circle cx="${p[0]}" cy="${p[1]}" r="5" class="attendance-chart-dot"/><text x="${p[0]}" y="${Math.max(14,p[1]-12)}" text-anchor="middle" class="attendance-chart-value">${Math.round(data[i][metric])}%</text>`).join('')}</svg>`;
}
function attendanceGroupRows(groups,weekKey){return groups.map(g=>{const s=attendanceGroupWeekStats(g,weekKey),trend=attendanceTrendText(attendanceGroupTrend(g,weekKey,4));return`<tr><td><div class="table-title"><span class="discipline-icon">${disciplineEmoji(g.discipline)}</span><div><b>${esc(g.name)}</b><small>${esc(g.day)} · ${esc(g.time)}</small></div></div></td><td>${esc(person(g.mentorId).name)}</td><td><b>${s.enrolled}/${s.capacity}</b><small class="attendance-table-sub">${attendancePct(s.fill)}</small></td><td>${s.hasData?s.expected:'—'}</td><td>${s.hasData?`<b>${s.actual}</b><small class="attendance-table-sub">основных ${s.present}</small>`:'—'}</td><td>${s.hasData?attendancePct(s.attendance):'—'}</td><td>${s.hasData?attendancePct(s.density):'—'}</td><td>${s.hasData?`${s.objective} / ${s.noShow}`:'—'}<small class="attendance-table-sub">уваж. / неявки</small></td><td><span class="attendance-trend">${trend}</span></td><td><div class="table-actions"><button data-action="attendanceSessionForGroup" data-id="${g.id}" title="Отметить тренировку">${ICONS.plus}</button><button data-action="attendanceRoster" data-id="${g.id}" title="Состав группы">${ICONS.users}</button></div></td></tr>`}).join('')}
function attendanceSignalsHtml(signals){return`<div class="attendance-signal-list">${signals.length?signals.slice(0,12).map(s=>`<article class="attendance-signal ${s.kind==='red'?'red':''}"><i></i><div><b>${esc(s.title)}</b><span>${esc(s.text)}</span></div>${s.groupId?`<button class="btn btn-small btn-ghost" data-action="attendanceSessionForGroup" data-id="${s.groupId}">Открыть</button>`:''}</article>`).join(''):'<div class="empty"><b>Критичных сигналов нет</b>Продолжайте отмечать каждую тренировку.</div>'}</div>`}
function attendanceOverview(groups,weekKey){const a=attendanceAggregate(groups,weekKey),series=attendanceWeekSeries(groups,weekKey,8),signals=attendanceSignals(groups,weekKey),forecastNext=attendanceForecast(groups,attendanceAddDays(weekKey,7));return`<div class="attendance-kpis">${attendanceMetric('Заполненность групп',attendancePct(a.fill),`${a.currentEnrolled}/${a.currentCapacity} закреплённых мест`,a.fill)}${attendanceMetric('Посещаемость',a.sessions?attendancePct(a.attendance):'—',`${a.present} пришли из ${a.expected} ожидаемых`,a.sessions?a.attendance:null)}${attendanceMetric('Фактическая плотность',a.sessions?attendancePct(a.density):'—',`${a.actual} фактических посещений`,a.sessions?a.density:null)}${attendanceMetric('Учёт недели',attendancePct(a.completeness),`${a.withData.length}/${a.groups} групп заполнено`,a.completeness,a.completeness<70?'attention':'')}</div><div class="grid-main"><section class="card pad"><div class="card-head"><div><h3>Динамика фактической плотности</h3><p>Последние 8 недель; пустая неделя не считается нулём</p></div></div>${attendanceTrendChart(series,'density')}</section><section class="card pad"><div class="card-head"><div><h3>Причины и дополнительные посещения</h3><p>Болезнь и отпуск не ухудшают KPI наставника</p></div></div>${attendanceReasonGrid(a)}<div class="attendance-next-forecast"><span>Следующая неделя</span><b>${forecastNext.low}–${forecastNext.high}</b><small>фактических посещений по текущему составу</small></div></section></div><section class="card pad"><div class="card-head"><div><h3>Что требует внимания</h3><p>Система разделяет проблему продаж, объективные пропуски и работу наставника</p></div><button class="btn btn-small btn-ghost" data-action="attendanceCreateTasks">Создать задачи из сигналов</button></div>${attendanceSignalsHtml(signals)}</section><section class="card pad"><div class="card-head"><div><h3>Группы этой недели</h3><p>Записано → ожидалось → пришло → причины → динамика</p></div></div><div class="table-wrap"><table class="data-table attendance-table"><thead><tr><th>Группа</th><th>Наставник</th><th>Записано</th><th>Ожидалось</th><th>Пришло</th><th>Посещаемость</th><th>Плотность</th><th>Пропуски</th><th>4 недели</th><th></th></tr></thead><tbody>${attendanceGroupRows(groups,weekKey)}</tbody></table></div></section>`}
function attendanceGroupsView(groups,weekKey){const a=attendanceAggregate(groups,weekKey);return`<div class="grid-4">${metricCard('Групп в контуре',String(groups.length),'По выбранной роли','groups')}${metricCard('Закреплено детей',String(a.currentEnrolled),`${a.currentCapacity} мест`,'users',a.fill)}${metricCard('Факт посещений',String(a.actual),`${a.sessions} тренировок отмечено`,'attendance')}${metricCard('Неявки',String(a.noShow),`${a.objective} уважительных причин`,'tasks')}</div><section class="card pad"><div class="card-head"><div><h3>Все группы</h3><p>Главная управленческая таблица недели</p></div></div><div class="table-wrap"><table class="data-table attendance-table"><thead><tr><th>Группа</th><th>Наставник</th><th>Записано</th><th>Ожидалось</th><th>Пришло</th><th>Посещаемость</th><th>Плотность</th><th>Пропуски</th><th>4 недели</th><th></th></tr></thead><tbody>${attendanceGroupRows(groups,weekKey)}</tbody></table></div></section>`}
function attendanceMentorsView(groups,weekKey){const rows=attendanceMentorIds(groups).map(mid=>attendanceMentorWeekStats(mid,weekKey));return`<div class="grid-4">${metricCard('Наставников',String(rows.length),'В доступном контуре','mentor')}${metricCard('Учёт тренировок',attendancePct(avg(rows.map(x=>x.logging))),'Доля отмеченных групп','attendance')}${metricCard('Обработка рисков',attendancePct(avg(rows.map(x=>x.followup))),'Выполнение задач по пропускам','tasks')}${metricCard('Средняя плотность',attendancePct(attendanceAggregate(groups,weekKey).density),'Не используется как штраф за болезни','users')}</div><section class="card pad"><div class="card-head"><div><h3>Еженедельная статистика наставников</h3><p>Абсолютные числа показаны рядом, но сравнение строится по процентам и на одно занятие</p></div></div><div class="table-wrap"><table class="data-table attendance-table"><thead><tr><th>Наставник</th><th>Группы</th><th>Отмечено</th><th>Заполненность</th><th>Посещаемость</th><th>Плотность</th><th>Уважительные</th><th>Неявки</th><th>Рабочий индекс</th></tr></thead><tbody>${rows.map(x=>`<tr><td><div class="table-title"><span class="avatar small">${esc(x.p.avatar||x.p.name?.[0]||'Н')}</span><div><b>${esc(x.p.name)}</b><small>${esc(x.p.area||x.p.title||'')}</small></div></div></td><td>${x.groups.length}</td><td>${x.agg.withData.length}/${x.groups.length}<small class="attendance-table-sub">${attendancePct(x.logging)}</small></td><td>${attendancePct(x.agg.fill)}</td><td>${x.agg.sessions?attendancePct(x.agg.attendance):'—'}</td><td>${x.agg.sessions?attendancePct(x.agg.density):'—'}</td><td>${x.agg.objective}</td><td>${x.agg.noShow}</td><td><b>${attendancePct(x.workIndex)}</b><small class="attendance-table-sub">учёт + реакция</small></td></tr>`).join('')}</tbody></table></div><p class="readable-note">Рабочий индекс не зависит от того, заболели ли дети. Он учитывает полноту отметок и выполнение задач по возврату/контакту.</p></section>`}
function attendanceLogView(groups,weekKey){const groupIds=new Set(groups.map(g=>g.id)),sessions=attendanceSessions().filter(s=>groupIds.has(s.groupId)&&attendanceInWeek(s.date,weekKey)).sort((a,b)=>String(b.date).localeCompare(String(a.date)));return`<section class="card pad"><div class="card-head"><div><h3>Журнал тренировок</h3><p>Каждая запись хранит снимок состава и вместимости на дату занятия</p></div><button class="btn btn-primary" data-action="attendanceAddSession">+ Отметить</button></div><div class="attendance-session-list">${sessions.length?sessions.map(s=>{const g=activeGroups().find(x=>x.id===s.groupId)||{name:'Удалённая группа',mentorId:''},c=attendanceSessionCounts(s);return`<article class="attendance-session"><div class="attendance-session-date"><b>${new Date(s.date+'T12:00:00').toLocaleDateString('ru-RU',{day:'2-digit',month:'short'})}</b><span>${s.mode==='planned'?'План':'Факт'}</span></div><div class="attendance-session-main"><b>${esc(g.name)}</b><small>${esc(person(g.mentorId).name)} · ожидалось ${c.expected} · пришло ${c.actual} · уваж. ${c.objective} · неявки ${c.noShow}</small></div><div class="attendance-session-metrics"><span>${attendancePct((Number(s.capacitySnapshot)||g.capacity)?c.actual/(Number(s.capacitySnapshot)||g.capacity)*100:0)} плотность</span></div><div class="table-actions"><button data-action="attendanceEditSession" data-id="${s.id}">${ICONS.edit}</button><button data-action="attendanceDeleteSession" data-id="${s.id}">${ICONS.trash}</button></div></article>`}).join(''):'<div class="empty"><b>Записей пока нет</b>После тренировки отметьте фактическое посещение.</div>'}</div></section>`}
function attendanceForecastView(groups,weekKey){const next=attendanceAddDays(weekKey,7),forecastData=attendanceForecast(groups,next),series=attendanceWeekSeries(groups,weekKey,8);return`<section class="attendance-forecast-hero"><div><div class="eyebrow">ПРОГНОЗ · ${esc(attendanceWeekLabel(next))}</div><h3>Ожидается ${Math.round(forecastData.base)} посещений</h3><p>Рабочий диапазон <b>${forecastData.low}–${forecastData.high}</b>. Это оценка, а не обещание точного числа.</p></div><div class="attendance-forecast-range"><span>Диапазон</span><b>${forecastData.low}–${forecastData.high}</b><small>по всем доступным группам</small></div></section><div class="grid-main"><section class="card pad"><div class="card-head"><div><h3>История посещаемости</h3><p>Посещаемость последних недель используется для прогноза</p></div></div>${attendanceTrendChart(series,'attendance')}</section><section class="card pad"><div class="card-head"><div><h3>Как читать прогноз</h3><p>Модель учитывает 4–8 недель и текущий состав</p></div></div><div class="compact-list"><div class="compact-item"><i class="item-dot"></i><div class="item-main"><b>Не выдаёт дробных детей</b><small>Показывает честный диапазон, например 4–6 человек.</small></div></div><div class="compact-item"><i class="item-dot"></i><div class="item-main"><b>Известные отсутствия уменьшают прогноз</b><small>Предварительные болезни, отпуск и заморозки можно внести как план.</small></div></div><div class="compact-item"><i class="item-dot"></i><div class="item-main"><b>Пустая неделя не равна нулю</b><small>Незаполненный журнал не портит историю.</small></div></div></div></section></div><section class="card pad"><div class="card-head"><div><h3>Прогноз следующей недели по группам</h3><p>Чем больше истории, тем выше уверенность</p></div></div><div class="table-wrap"><table class="data-table attendance-table"><thead><tr><th>Группа</th><th>Наставник</th><th>Записано</th><th>Прогноз</th><th>Уверенность</th><th>Основание</th><th>Известно отсутствий</th></tr></thead><tbody>${forecastData.rows.map(x=>`<tr><td><b>${esc(x.group.name)}</b><small class="attendance-table-sub">${esc(x.group.day)} · ${esc(x.group.time)}</small></td><td>${esc(person(x.group.mentorId).name)}</td><td>${attendanceEnrolled(x.group)}</td><td><b>${x.low}–${x.high}</b></td><td>${esc(x.confidence)}</td><td>${esc(x.method)}</td><td>${x.knownAbs}</td></tr>`).join('')}</tbody></table></div></section>`}
function attendanceArchiveView(groups,weekKey){const list=attendanceArchives().sort((a,b)=>String(b.weekKey).localeCompare(String(a.weekKey)));return`<section class="card pad"><div class="card-head"><div><h3>Архив закрытых недель</h3><p>Снимок больше не меняется при переводе ребёнка или редактировании группы</p></div><button class="btn btn-primary" data-action="attendanceCloseWeek">Закрыть ${esc(attendanceWeekLabel(weekKey))}</button></div>${list.length?`<div class="attendance-archive-grid">${list.map(a=>`<article class="attendance-archive-card"><div class="eyebrow">${esc(a.weekKey)}</div><h4>${esc(a.label||attendanceWeekLabel(a.weekKey))}</h4><div class="attendance-archive-kpis"><div><span>Заполненность</span><b>${attendancePct(a.metrics?.fill||0)}</b></div><div><span>Посещаемость</span><b>${attendancePct(a.metrics?.attendance||0)}</b></div><div><span>Плотность</span><b>${attendancePct(a.metrics?.density||0)}</b></div><div><span>Тренировки</span><b>${a.metrics?.sessions||0}</b></div></div>${a.comment?`<p>${esc(a.comment)}</p>`:''}</article>`).join('')}</div>`:'<div class="empty"><b>Закрытых недель пока нет</b>В конце воскресенья сохраните итог и комментарий.</div>'}</section>`}
function renderAttendance(){const groups=attendanceScopeGroups(),weekKey=attendanceSelectedWeek(),tab=state.ui.attendanceTab||'overview';let body='';if(tab==='overview')body=attendanceOverview(groups,weekKey);if(tab==='groups')body=attendanceGroupsView(groups,weekKey);if(tab==='mentors')body=attendanceMentorsView(groups,weekKey);if(tab==='log')body=attendanceLogView(groups,weekKey);if(tab==='forecast')body=attendanceForecastView(groups,weekKey);if(tab==='archive')body=attendanceArchiveView(groups,weekKey);return`<div class="page readable-page attendance-page">${pageHead('ЕЖЕНЕДЕЛЬНЫЙ КОНТРОЛЬ','Посещаемость и плотность',`${attendanceWeekLabel(weekKey)}: записано, ожидалось, пришло, причины и динамика`)}${attendanceWeekToolbar()}${attendanceTabs(tab)}${body}</div>`}

function attendanceStatusOptions(selected='unknown'){return Object.entries(ATTENDANCE_STATUS).map(([v,l])=>`<option value="${v}" ${selected===v?'selected':''}>${esc(l)}</option>`).join('')}
function attendanceSessionModal(item=null,groupId='',dateValue=''){
  const groups=attendanceScopeGroups(),group=groups.find(g=>g.id===(item?.groupId||groupId))||groups[0];if(!group){toast('Нет доступных групп','Сначала добавьте группу.','error');return}
  const date=dateValue||item?.date||attendanceWeekDateForGroup(group),members=attendanceMembers(group.id),counts=item?attendanceSessionCounts(item):null,enrolled=attendanceEnrolled(group),future=date>today(),mode=item?.mode||(future?'planned':'actual');
  const rosterHtml=members.length?`<div class="span-2 attendance-roster-editor"><div class="attendance-roster-head"><div><b>Состав группы · ${members.length}</b><small>${group.rosterManaged?'официальный состав':'частичный список; заполненность не уменьшается ниже числа в карточке группы'}</small></div><button type="button" class="btn btn-small btn-ghost" data-action="attendanceRoster" data-id="${group.id}">Управление составом</button></div>${members.map(({child})=>{const record=(item?.records||[]).find(r=>r.childId===child.id);return`<label class="attendance-child-row"><span>${esc(child.name)}</span><select class="select" data-att-child="${child.id}">${attendanceStatusOptions(record?.status||'unknown')}</select></label>`}).join('')}</div>`:`<div class="span-2 attendance-no-roster"><b>Именной состав пока не внесён</b><span>Можно работать по общим числам. Для автоматического поиска повторных пропусков добавьте детей в состав группы.</span><button type="button" class="btn btn-small btn-ghost" data-action="attendanceRoster" data-id="${group.id}">Добавить состав</button></div>`;
  const aggregate=!members.length?`<div class="field"><label>Ожидалось</label><input class="input" type="number" min="0" name="expectedCount" value="${counts?.expected??enrolled}"></div><div class="field"><label>Пришли из состава</label><input class="input" type="number" min="0" name="presentCount" value="${counts?.present??0}"></div><div class="field"><label>Заболели</label><input class="input" type="number" min="0" name="sickCount" value="${counts?.sick??0}"></div><div class="field"><label>Предупредили</label><input class="input" type="number" min="0" name="warnedCount" value="${counts?.warned??0}"></div><div class="field"><label>Отпуск</label><input class="input" type="number" min="0" name="vacationCount" value="${counts?.vacation??0}"></div><div class="field"><label>Заморозка</label><input class="input" type="number" min="0" name="freezeCount" value="${counts?.freeze??0}"></div><div class="field"><label>Неявка без предупреждения</label><input class="input" type="number" min="0" name="noShowCount" value="${counts?.noShow??0}"></div>`:'';
  openModal({title:item?'Изменить посещаемость':'Отметить тренировку',subtitle:`${group.name} · ${group.day} ${group.time}`,body:`<form id="attendanceSessionForm" data-id="${esc(item?.id||'')}" class="form-grid"><div class="field"><label>Группа</label><select class="select" name="groupId" data-filter="attendanceModalGroup">${groups.map(g=>`<option value="${g.id}" ${g.id===group.id?'selected':''}>${esc(person(g.mentorId).name)} · ${esc(g.name)} · ${esc(g.day)} ${esc(g.time)}</option>`).join('')}</select></div><div class="field"><label>Дата</label><input class="input" type="date" name="date" value="${date}" required></div><div class="field span-2"><label>Тип записи</label><select class="select" name="mode"><option value="actual" ${mode==='actual'?'selected':''}>Факт проведённой тренировки</option><option value="planned" ${mode==='planned'?'selected':''}>План / известные отсутствия</option></select></div>${rosterHtml}${aggregate}<div class="field"><label>Отработки</label><input class="input" type="number" min="0" name="makeupCount" value="${counts?.makeup??0}"></div><div class="field"><label>Пробные</label><input class="input" type="number" min="0" name="trialCount" value="${counts?.trial??0}"></div><div class="field"><label>Гости</label><input class="input" type="number" min="0" name="guestCount" value="${counts?.guest??0}"></div><div class="field span-2"><label>Комментарий</label><textarea class="textarea" name="notes" placeholder="Причины, особенности тренировки, что сделать дальше">${esc(item?.notes||'')}</textarea></div><div class="attendance-form-summary span-2"><span>Вместимость: <b>${group.capacity||0}</b></span><span>Закреплено: <b>${enrolled}</b></span><span>Неделя: <b>${esc(attendanceWeekLabel(attendanceWeekStart(date)))}</b></span></div>${formActions(item?'Сохранить':'Добавить')}</form>`});
}
function attendanceRosterModal(groupId){const group=attendanceScopeGroups().find(g=>g.id===groupId)||activeGroups().find(g=>g.id===groupId);if(!group)return;const members=attendanceMembers(group.id);openModal({title:`Состав · ${group.name}`,subtitle:`${person(group.mentorId).name} · ${group.day} ${group.time}`,body:`<div class="attendance-roster-manage"><div class="attendance-roster-summary"><div><span>В карточке группы</span><b>${group.students||0}</b></div><div><span>Имен в списке</span><b>${members.length}</b></div><div><span>Для аналитики</span><b>${attendanceEnrolled(group)}</b></div></div><div class="compact-list">${members.length?members.map(({child,membership})=>`<div class="compact-item"><span class="avatar small">${esc(child.name.slice(0,2))}</span><div class="item-main"><b>${esc(child.name)}</b><small>${esc(child.parentContact||'контакт не указан')}</small></div><button class="task-delete" data-action="attendanceRemoveMember" data-id="${membership.id}" title="Убрать из группы">${ICONS.trash}</button></div>`).join(''):'<div class="empty"><b>Список пуст</b>Добавьте детей, чтобы видеть повторные пропуски поимённо.</div>'}</div><label class="check attendance-roster-mode"><input type="checkbox" data-action="attendanceRosterManaged" data-id="${group.id}" ${group.rosterManaged?'checked':''}> Список полный — считать его официальным составом группы</label><div class="form-actions"><button class="btn btn-ghost" data-action="closeModal">Закрыть</button><button class="btn btn-primary" data-action="attendanceAddChild" data-group="${group.id}">+ Добавить ребёнка</button></div></div>`})}
function attendanceChildModal(groupId=''){const groups=attendanceScopeGroups(),selected=groups.find(g=>g.id===groupId)||groups[0];if(!selected)return;openModal({title:'Добавить ребёнка в группу',subtitle:'Имя хранится в общей зашифрованной базе',body:`<form id="attendanceChildForm" class="form-grid"><div class="field span-2"><label>Имя ребёнка</label><input class="input" name="name" required></div><div class="field span-2"><label>Группа</label><select class="select" name="groupId">${groups.map(g=>`<option value="${g.id}" ${g.id===selected.id?'selected':''}>${esc(person(g.mentorId).name)} · ${esc(g.name)} · ${esc(g.day)} ${esc(g.time)}</option>`).join('')}</select></div><div class="field span-2"><label>Контакт родителя</label><input class="input" name="parentContact" placeholder="Телефон или имя в CRM — необязательно"></div><div class="field"><label>Дата начала</label><input class="input" type="date" name="startDate" value="${today()}"></div><div class="field span-2"><label>Комментарий</label><textarea class="textarea" name="notes"></textarea></div>${formActions('Добавить')}</form>`})}
function attendanceCloseWeekModal(){const weekKey=attendanceSelectedWeek(),groups=attendanceScopeGroups(),a=attendanceAggregate(groups,weekKey),old=attendanceArchives().find(x=>x.weekKey===weekKey);openModal({title:`Закрыть неделю`,subtitle:attendanceWeekLabel(weekKey),body:`<form id="attendanceCloseWeekForm" data-id="${old?.id||''}" class="form-grid"><div class="attendance-close-preview span-2"><div><span>Заполненность</span><b>${attendancePct(a.fill)}</b></div><div><span>Посещаемость</span><b>${attendancePct(a.attendance)}</b></div><div><span>Плотность</span><b>${attendancePct(a.density)}</b></div><div><span>Тренировки</span><b>${a.sessions}</b></div></div><div class="field span-2"><label>Итоги и решения на следующую неделю</label><textarea class="textarea" name="comment" placeholder="Что сработало, какие группы требуют продаж, кому нужно позвонить">${esc(old?.comment||'')}</textarea></div>${formActions(old?'Обновить снимок':'Закрыть неделю')}</form>`})}

const __renderDashboardAttendanceBase=renderDashboard;renderDashboard=function(){const base=__renderDashboardAttendanceBase(),groups=attendanceScopeGroups(),a=attendanceAggregate(groups,attendanceSelectedWeek());const panel=`<section class="card pad attendance-dashboard-panel"><div class="card-head"><div><h3>Посещаемость этой недели</h3><p>Записано, пришло и фактическая плотность — отдельно от обычной загрузки</p></div><button class="btn btn-small btn-ghost" data-view="attendance">Открыть</button></div><div class="attendance-mini-grid"><div><span>Заполненность</span><b>${attendancePct(a.fill)}</b></div><div><span>Посещаемость</span><b>${a.sessions?attendancePct(a.attendance):'—'}</b></div><div><span>Плотность</span><b>${a.sessions?attendancePct(a.density):'—'}</b></div><div><span>Неявки</span><b>${a.noShow}</b></div></div></section>`;return appendBeforePageClose(base,panel)};
const __renderAnalyticsAttendanceBase=renderAnalytics;renderAnalytics=function(){const base=__renderAnalyticsAttendanceBase(),groups=attendanceScopeGroups(),week=attendanceSelectedWeek(),a=attendanceAggregate(groups,week),f=attendanceForecast(groups,attendanceAddDays(week,7));const panel=`<section class="card pad"><div class="card-head"><div><h3>Посещаемость и прогноз следующей недели</h3><p>Фактическая плотность ${a.sessions?attendancePct(a.density):'ещё не заполнена'} · прогноз ${f.low}–${f.high} посещений</p></div><button class="btn btn-small btn-ghost" data-view="attendance">Подробная аналитика</button></div>${attendanceTrendChart(attendanceWeekSeries(groups,week,8),'attendance')}</section>`;return appendBeforePageClose(base,panel)};
const __renderStasAttendanceBase=renderStas;renderStas=function(){const base=__renderStasAttendanceBase(),groups=attendanceScopeGroups(),a=attendanceAggregate(groups,attendanceSelectedWeek());const panel=`<section class="card pad"><div class="card-head"><div><h3>Роллер-школа · неделя</h3><p>Болезни не снижают оценку наставников; контролируются учёт и реакция</p></div><button class="btn btn-small btn-ghost" data-view="attendance">Посещаемость</button></div><div class="attendance-mini-grid"><div><span>Отмечено групп</span><b>${a.withData.length}/${a.groups}</b></div><div><span>Посещаемость</span><b>${a.sessions?attendancePct(a.attendance):'—'}</b></div><div><span>Плотность</span><b>${a.sessions?attendancePct(a.density):'—'}</b></div><div><span>Неявки</span><b>${a.noShow}</b></div></div></section>`;return appendBeforePageClose(base,panel)};
const __renderMentorAttendanceBase=renderMentor;renderMentor=function(){const base=__renderMentorAttendanceBase(),groups=attendanceScopeGroups(),a=attendanceAggregate(groups,attendanceSelectedWeek());const panel=`<section class="card pad"><div class="card-head"><div><h3>Моя неделя · посещаемость</h3><p>Отметьте факт после каждой тренировки</p></div><button class="btn btn-small btn-primary" data-view="attendance">Открыть журнал</button></div><div class="attendance-mini-grid"><div><span>Групп отмечено</span><b>${a.withData.length}/${a.groups}</b></div><div><span>Пришло</span><b>${a.actual}</b></div><div><span>Уважительные</span><b>${a.objective}</b></div><div><span>Неявки</span><b>${a.noShow}</b></div></div></section>`;return appendBeforePageClose(base,panel)};
const __renderAdminAttendanceBase=renderAdmin;renderAdmin=function(){const base=__renderAdminAttendanceBase(),groups=attendanceScopeGroups(),signals=attendanceSignals(groups,attendanceSelectedWeek()).filter(x=>x.childId||x.kind==='red');const panel=`<section class="card pad"><div class="card-head"><div><h3>Кого вернуть на тренировку</h3><p>Повторные пропуски и неявки из журнала наставников</p></div><button class="btn btn-small btn-ghost" data-view="attendance">Все сигналы</button></div>${attendanceSignalsHtml(signals.slice(0,6))}</section>`;return appendBeforePageClose(base,panel)};

const __renderCurrentViewAttendanceBase=renderCurrentView;renderCurrentView=function(){if(currentView==='attendance'){if(!allowedView('attendance'))currentView=roleInfo().start;else{$('#pageTitle').textContent='Посещаемость';$('#pages').innerHTML=renderAttendance();renderNav();animateNumbers();return}}return __renderCurrentViewAttendanceBase()};

const __handleSubmitAttendanceBase=handleSubmit;handleSubmit=function(e){const f=e.target;if(!(f instanceof HTMLFormElement))return __handleSubmitAttendanceBase(e);const v=formValues(f),stamp=nowIso();
  if(f.id==='attendanceSessionForm'){e.preventDefault();const group=activeGroups().find(g=>g.id===v.groupId);if(!group)return;const old=state.attendanceSessions.find(x=>x.id===f.dataset.id);const records=[...f.querySelectorAll('[data-att-child]')].map(sel=>({childId:sel.dataset.attChild,status:sel.value,nameSnapshot:attendanceChildren().find(c=>c.id===sel.dataset.attChild)?.name||'',updatedAt:stamp}));let expected=num(v.expectedCount),present=num(v.presentCount),sick=num(v.sickCount),warned=num(v.warnedCount),vacation=num(v.vacationCount),freeze=num(v.freezeCount),noShow=num(v.noShowCount);if(records.length){const c=k=>records.filter(r=>r.status===k).length;present=c('present');sick=c('sick');warned=c('warned');vacation=c('vacation');freeze=c('freeze');noShow=c('noShow');expected=present+sick+warned+noShow+c('unknown')}expected=Math.max(expected,present+sick+warned+noShow);const item={...(old||{}),id:old?.id||id('attendance'),groupId:group.id,date:v.date,weekKey:attendanceWeekStart(v.date),mode:v.mode||'actual',status:'completed',enrolledSnapshot:attendanceEnrolled(group),capacitySnapshot:Number(group.capacity)||0,expectedCount:expected,presentCount:present,sickCount:sick,warnedCount:warned,vacationCount:vacation,freezeCount:freeze,noShowCount:noShow,makeupCount:num(v.makeupCount),trialCount:num(v.trialCount),guestCount:num(v.guestCount),records,notes:v.notes,createdAt:old?.createdAt||stamp,updatedAt:stamp};upsert(state.attendanceSessions,item);state.ui.attendanceWeek=item.weekKey;const made=attendanceReconcileTasks(item.weekKey);closeModal();touch(`Посещаемость: ${group.name}${made?` · создано задач ${made}`:''}`);return}
  if(f.id==='attendanceChildForm'){e.preventDefault();const child={id:id('child'),name:v.name,parentContact:v.parentContact,notes:v.notes,active:true,createdAt:stamp,updatedAt:stamp};state.attendanceChildren.push(child);state.attendanceMemberships.push({id:id('membership'),childId:child.id,groupId:v.groupId,startDate:v.startDate||today(),status:'active',createdAt:stamp,updatedAt:stamp});const g=activeGroups().find(x=>x.id===v.groupId),count=attendanceMembers(v.groupId).length;if(g){if(g.rosterManaged)g.students=count;else g.students=Math.max(Number(g.students)||0,count);g.updatedAt=stamp}closeModal();touch(`Добавлен в состав: ${child.name}`);attendanceRosterModal(v.groupId);return}
  if(f.id==='attendanceCloseWeekForm'){e.preventDefault();const weekKey=attendanceSelectedWeek(),groups=attendanceScopeGroups(),a=attendanceAggregate(groups,weekKey),mentorRows=attendanceMentorIds(groups).map(mid=>attendanceMentorWeekStats(mid,weekKey)),old=state.attendanceWeekArchives.find(x=>x.id===f.dataset.id||x.weekKey===weekKey);const item={...(old||{}),id:old?.id||id('weekArchive'),weekKey,label:attendanceWeekLabel(weekKey),scope:currentRole,metrics:{fill:a.fill,attendance:a.attendance,density:a.density,sessions:a.sessions,expected:a.expected,present:a.present,actual:a.actual,objective:a.objective,noShow:a.noShow,completeness:a.completeness},groups:a.stats.map(x=>({groupId:x.group.id,name:x.group.name,mentorId:x.group.mentorId,enrolled:x.enrolled,capacity:x.capacity,expected:x.expected,present:x.present,actual:x.actual,fill:x.fill,attendance:x.attendance,density:x.density,objective:x.objective,noShow:x.noShow,sessions:x.sessionCount})),mentors:mentorRows.map(x=>({mentorId:x.mentorId,name:x.p.name,logging:x.logging,followup:x.followup,workIndex:x.workIndex,attendance:x.agg.attendance,density:x.agg.density})),comment:v.comment,closedAt:stamp,updatedAt:stamp};upsert(state.attendanceWeekArchives,item);const made=attendanceReconcileTasks(weekKey);closeModal();touch(`Закрыта неделя ${attendanceWeekLabel(weekKey)}${made?` · задач ${made}`:''}`);return}
  return __handleSubmitAttendanceBase(e)
};

const __handleClickAttendanceBase=handleClick;handleClick=function(e){const el=e.target.closest('[data-action]');if(el){const a=el.dataset.action;
  if(a==='attendanceTab'){state.ui.attendanceTab=el.dataset.tab;persistLocal();renderCurrentView();return}
  if(a==='attendancePrevWeek'){state.ui.attendanceWeek=attendanceAddDays(attendanceSelectedWeek(),-7);persistLocal();renderCurrentView();return}
  if(a==='attendanceNextWeek'){state.ui.attendanceWeek=attendanceAddDays(attendanceSelectedWeek(),7);persistLocal();renderCurrentView();return}
  if(a==='attendanceCurrentWeek'){state.ui.attendanceWeek=attendanceWeekStart(today());persistLocal();renderCurrentView();return}
  if(a==='attendanceAddSession'){attendanceSessionModal();return}
  if(a==='attendanceSessionForGroup'){attendanceSessionModal(null,el.dataset.id);return}
  if(a==='attendanceEditSession'){attendanceSessionModal(state.attendanceSessions.find(x=>x.id===el.dataset.id));return}
  if(a==='attendanceDeleteSession'){const x=state.attendanceSessions.find(s=>s.id===el.dataset.id);if(x&&confirm('Удалить запись посещаемости?')){x.deletedAt=nowIso();x.updatedAt=nowIso();touch('Запись посещаемости удалена')}return}
  if(a==='attendanceRoster'){attendanceRosterModal(el.dataset.id);return}
  if(a==='attendanceAddChild'){attendanceChildModal(el.dataset.group||'');return}
  if(a==='attendanceRemoveMember'){const m=state.attendanceMemberships.find(x=>x.id===el.dataset.id);if(m&&confirm('Убрать ребёнка из этой группы?')){m.deletedAt=nowIso();m.updatedAt=nowIso();const g=activeGroups().find(x=>x.id===m.groupId);if(g?.rosterManaged){g.students=attendanceMembers(g.id).length;g.updatedAt=nowIso()}touch('Состав группы обновлён');attendanceRosterModal(m.groupId)}return}
  if(a==='attendanceRosterManaged'){return}
  if(a==='attendanceCreateTasks'){const made=attendanceReconcileTasks(attendanceSelectedWeek());if(made)touch(`Создано задач по посещаемости: ${made}`);else toast('Новых задач нет','Все текущие сигналы уже обработаны или не требуют задачи.');return}
  if(a==='attendanceCloseWeek'){attendanceCloseWeekModal();return}
 }
 return __handleClickAttendanceBase(e)};
const __handleChangeAttendanceBase=handleChange;handleChange=function(e){const el=e.target;
  if(el.dataset.filter==='attendanceModalGroup'){attendanceSessionModal(null,el.value,$('#attendanceSessionForm [name="date"]')?.value||attendanceWeekDateForGroup(activeGroups().find(g=>g.id===el.value)));return}
  if(el.dataset.action==='attendanceRosterManaged'){const g=activeGroups().find(x=>x.id===el.dataset.id);if(g){g.rosterManaged=el.checked;g.students=el.checked?attendanceMembers(g.id).length:Math.max(Number(g.students)||0,attendanceMembers(g.id).length);g.updatedAt=nowIso();touch(`Состав группы ${g.name}: ${el.checked?'официальный':'частичный'}`);attendanceRosterModal(g.id)}return}
  return __handleChangeAttendanceBase(e)};

const __navBadgeAttendanceBase=navBadge;navBadge=function(view){if(view==='attendance'){const a=attendanceAggregate(attendanceScopeGroups(),attendanceSelectedWeek());return a.noShow||attendanceSignals(attendanceScopeGroups(),attendanceSelectedWeek()).filter(x=>x.kind==='red').length||''}return __navBadgeAttendanceBase(view)};
const __bootAttendanceBase=boot;boot=async function(){const result=await __bootAttendanceBase();if(window.EKGrowthOS)window.EKGrowthOS={...window.EKGrowthOS,attendanceBuild:ATTENDANCE_EXTENSION_BUILD,attendanceWeek:week=>attendanceAggregate(attendanceScopeGroups(),attendanceWeekStart(week||today())),attendanceForecast:week=>attendanceForecast(attendanceScopeGroups(),attendanceWeekStart(week||attendanceAddDays(today(),7)))};return result};
// ATTENDANCE_INTELLIGENCE_V1_END
